betagouv/mon-aide-cyber

- mon-aide-cyber-ui/src/composants/ComposantDiagnostique.tsx
- mon-aide-cyber-ui/src/composants/intercepteurs/ComposantDiagnostiqueIntercepteur.tsx
- mon-aide-cyber-ui/src/composants/intercepteurs/ComposantIntercepteur.tsx
- mon-aide-cyber-ui/src/main.tsx
- mon-aide-cyber-ui/src/stories/Diagnostique.stories.tsx
Charge les composants depuis le routeur React sans avoir de dépendance à `React-Router` au sein de nos composants
> [REMANIEMENT] Intercepteur composant générique

- mon-aide-cyber-ui/src/assets/styles/_questionnaire.scss
- mon-aide-cyber-ui/src/composants/ComposantDiagnostique.tsx
Conformément à la discussion autour du langage à utiliser
> [REMANIEMENT] Renomme la classe css question-secondaire en question-tiroir

- mon-aide-cyber-api/src/adaptateurs/AdaptateurReferentiel.ts
- mon-aide-cyber-api/src/diagnostique/ServiceDiagnostique.ts
- mon-aide-cyber-api/src/infrastructure/adaptateurs/AdaptateurReferentielMAC.ts
- mon-aide-cyber-api/test/adaptateurs/AdaptateurReferentielDeTest.ts
- mon-aide-cyber-api/test/api/testRouteDiagnostique.spec.ts
- mon-aide-cyber-api/test/diagnostique/ServiceDiagnostique.spec.ts
`AdaptateurReferentiel::lis()` retournait un `object`, il retourne maintenant un `Referentiel`
> [REMANIEMENT] Corrige la signature de la méthode 'lis' de l'adaptateur référentiel

- mon-aide-cyber-ui/src/App.tsx
- mon-aide-cyber-ui/src/composants/diagnostic/ComposantDiagnostique.tsx
- mon-aide-cyber-ui/src/composants/diagnostic/ComposantLancerDiagnostic.tsx
- mon-aide-cyber-ui/src/domaine/Entrepots.ts
- mon-aide-cyber-ui/src/domaine/diagnostique/Diagnostique.ts
- mon-aide-cyber-ui/src/infrastructure/entrepots/EntrepotsAPI.ts
- mon-aide-cyber-ui/src/main.tsx
- mon-aide-cyber-ui/src/stories/Diagnostique.stories.tsx
- mon-aide-cyber-ui/src/stories/ErreurDiagnostique.stories.tsx
- mon-aide-cyber-ui/test/infrastructure/entrepots/EntrepotsMemoire.ts
En cliquant sur le bouton `Lancer un diagnostic`, l'API lance le diagnostic et l'utilisateur est redirigé vers le diagnostic correspondant
> [DIAGNOSTIC] Ajoute un bouton pour lancer un diagnostic

- mon-aide-cyber-api/src/api/representateurs/representateurDiagnostic.ts
- mon-aide-cyber-api/src/api/representateurs/types.ts
- mon-aide-cyber-api/src/diagnostic/donneesReferentiel.ts
- mon-aide-cyber-api/src/infrastructure/adaptateurs/adaptateurTranscripteur.ts
- mon-aide-cyber-api/test/api/representateurs/representateurDiagnostic.spec.ts
- mon-aide-cyber-api/test/api/representateurs/transcripteursDeTest.ts
- mon-aide-cyber-ui/src/composants/diagnostic/ComposantDiagnostic.tsx
- mon-aide-cyber-ui/src/domaine/diagnostic/Referentiel.ts
- mon-aide-cyber-ui/src/stories/Diagnostic.stories.tsx
- mon-aide-cyber-ui/test/consructeurs/constructeurQuestions.ts
La question sur la `cyberattaque` contient une question à tiroir à choix unique (`Si "Oui": avez-vous déposé plainte ou réalisé un signalement auprès d'un service judiciaire ?`). 
Dans la capture ci-dessous, on peut voir que les réponses à cette question sont des cases à cocher alors qu’elles devraient être des boutons radio.
> [CORRECTION] Fixe la représentation des questions à tiroir à choix unique

- mon-aide-cyber-api/package.json
- mon-aide-cyber-api/src/api/routesAPIDiagnostic.ts
- mon-aide-cyber-api/src/diagnostic/Referentiel.ts
- mon-aide-cyber-api/src/diagnostic/ServiceDiagnostic.ts
- mon-aide-cyber-api/test/api/executeurRequete.ts
- mon-aide-cyber-api/test/api/routesAPIDiagnostic.spec.ts
- package-lock.json
On peut envoyer une réponse pour une question à choix unique qui se trouve à la racine d’une thématique du référentiel
> [DIAGNOSTIC] Persiste la réponse donnée pour une question à choix unique

- mon-aide-cyber-api/src/api/representateurs/representateurDiagnostic.ts
- mon-aide-cyber-api/src/api/representateurs/types.ts
- mon-aide-cyber-api/test/api/representateurs/representateurDiagnostic.spec.ts
- mon-aide-cyber-api/test/api/representateurs/transcripteursDeTest.ts
- mon-aide-cyber-ui/src/composants/diagnostic/ComposantDiagnostic.tsx
- mon-aide-cyber-ui/src/domaine/diagnostic/Diagnostic.ts
- mon-aide-cyber-ui/src/domaine/diagnostic/Referentiel.ts
- mon-aide-cyber-ui/src/domaine/diagnostic/reducteurReponse.ts
- mon-aide-cyber-ui/src/infrastructure/entrepots/EntrepotsAPI.ts
- mon-aide-cyber-ui/src/stories/ReponsesDonneesAuDiagnostic.stories.tsx
- mon-aide-cyber-ui/test/consructeurs/constructeurActionDiagnostic.ts
- mon-aide-cyber-ui/test/consructeurs/constructeurQuestions.ts
- mon-aide-cyber-ui/test/consructeurs/constructeurReferentiel.ts
- mon-aide-cyber-ui/test/consructeurs/constructeurReponsePossible.ts
- mon-aide-cyber-ui/test/domaine/diagnostic/reducteurReponse.spec.ts
- mon-aide-cyber-ui/test/infrastructure/entrepots/EntrepotsMemoire.ts
- L’API renvoie l’action `repondre` dans la réponse d’une requête d’un diagnostic
- L’UI envoie la réponse
> [DIAGNOSTIC] Envoie une réponse à une question à choix unique depuis l’UI

- mon-aide-cyber-api/src/api/representateurs/representateurDiagnostic.ts
- mon-aide-cyber-api/src/api/routesAPIDiagnostic.ts
- mon-aide-cyber-api/src/diagnostic/Diagnostic.ts
- mon-aide-cyber-api/src/diagnostic/Referentiel.ts
- mon-aide-cyber-api/src/diagnostic/ServiceDiagnostic.ts
- mon-aide-cyber-api/test/constructeurs/constructeurDiagnostic.ts
- mon-aide-cyber-api/test/diagnostic/ServiceDiagnostic.spec.ts
Afin de découpler le référentiel, qui contient le corps des questions, du diagnostic qui comprend les questions avec leurs réponses.
NB: Lorsqu’on lance un diagnostic pour la première fois, les réponses données sont valorisées à null
> [REMANIEMENT] Modifie le typage du diagnostic

- mon-aide-cyber-ui/src/composants/diagnostic/ComposantDiagnostic.tsx
- mon-aide-cyber-ui/src/domaine/diagnostic/Diagnostic.ts
- mon-aide-cyber-ui/src/domaine/diagnostic/Referentiel.ts
- mon-aide-cyber-ui/src/domaine/diagnostic/reducteurReponse.ts
- mon-aide-cyber-ui/src/stories/AfficheDiagnostic.stories.tsx
- mon-aide-cyber-ui/src/stories/ReponsesDonneesAuDiagnostic.stories.tsx
- mon-aide-cyber-ui/test/consructeurs/constructeurReferentiel.ts
- mon-aide-cyber-ui/test/domaine/diagnostic/reducteurReponse.spec.ts
- mon-aide-cyber-ui/test/infrastructure/entrepots/EntrepotsMemoire.ts
**Contexte:**
Afficher la page d’un diagnostic
**Étapes pour reproduire:**
- Ouvrir la console développeur de son navigateur
- Aller dans l’onglet réseau de la console
- Aller sur la page d’un diagnostic
**Résultat constaté:**
Il y a de multiples requêtes de réponse au diagnostic dans l’onglet réseau
**Résultat attendu:**
On ne doit voir que la requête de récupération du diagnostic au chargement du diagnostic
> [CORRECTION] Évite l’appel à l’API pour ajouter des réponses au chargement du diagnostic

- mon-aide-cyber-ui/src/composants/diagnostic/ComposantDiagnostic.tsx
- mon-aide-cyber-ui/src/domaine/diagnostic/reducteurReponse.ts
- mon-aide-cyber-ui/src/stories/ReponsesDonneesAuDiagnostic.stories.tsx
- mon-aide-cyber-ui/test/domaine/diagnostic/constructeurEtaReponse.ts
- mon-aide-cyber-ui/test/domaine/diagnostic/reducteurReponse.spec.ts
Pour les questions à tiroir nécessitant une réponse unique (cf capture ci-dessous), on s'assure de n'envoyer qu'une seule réponse.
> [DIAGNOSTIC] Prends en compte les réponses uniques pour les questions à tiroir

- mon-aide-cyber-ui/src/domaine/diagnostic/reducteurReponse.ts
- mon-aide-cyber-ui/src/stories/ReponsesDonneesAuDiagnostic.stories.tsx
- mon-aide-cyber-ui/test/domaine/diagnostic/reducteurReponse.spec.ts
Pour une question à choix unique ayant des réponses avec question à tiroir, les réponses des questions à tiroir étaient conservées lorsque l'on change les réponses.
**Exemple:**
> [CORRECTION] Corrige la saisie des questions à réponses uniques 

- mon-aide-cyber-api/package.json
- mon-aide-cyber-api/src/serveur.ts
- mon-aide-cyber-api/test/api/executeurRequete.ts
- mon-aide-cyber-api/test/api/routeAPIDiagnostics.spec.ts
- mon-aide-cyber-api/test/api/routesAPIDiagnostic.spec.ts
- mon-aide-cyber-api/test/api/testeurIntegration.ts
- package-lock.json
- Sur la CI, les tests sur le réseau (en HTTP) cassent aléatoirement (address already in use)
- On utilise une librairie d'injection pour éviter des appels sur la couche HTTP
> [CORRECTION] Corrige les tests d'intégration pour les appels d'API

- mon-aide-cyber-api/src/diagnostic/MoteurDeRecommandations.ts
- mon-aide-cyber-api/test/diagnostic/MoteurDeRecommandations.spec.ts
- mon-aide-cyber-ui/test/constructeurs/constructeurQuestions.ts
Des questions comportant plusieurs réponses contenant plusieurs questions à tiroir génère 2 même recommandations pour la question (cf captures ci-dessous)
**Exemple de question avec 2 réponses contenant des questions à tiroir:**
**Réponses données et résultat obtenu lorsque l'on génère le diagnostic:**
> [CORRECTION] Corrige la génération des recommandations pour s'assurer qu'une seule recommandation par question est donnée

- mon-aide-cyber-api/src/diagnostic/ServiceDiagnostic.ts
- mon-aide-cyber-api/src/domaine/BusEvenement.ts
- mon-aide-cyber-api/src/infrastructure/horloge/FournisseurHorloge.ts
- mon-aide-cyber-api/test/diagnostic/ServiceDiagnostic.spec.ts
- mon-aide-cyber-api/test/infrastructure/bus/BusEvenementDeTest.ts
- mon-aide-cyber-api/test/infrastructure/horloge/FournisseurHorlogeDeTest.ts
- afin de mettre à disposition une file pour contacter des services tiers pour un événement donné
> [REMANIEMENT] Introduis un bus d'événement

- mon-aide-cyber-ui/package.json
- mon-aide-cyber-ui/src/composants/diagnostic/ComposantDiagnostic.tsx
- mon-aide-cyber-ui/src/domaine/diagnostic/reducteurReponse.ts
- mon-aide-cyber-ui/test/domaine/diagnostic/constructeurEtaReponse.ts
- mon-aide-cyber-ui/test/domaine/diagnostic/reducteurDiagnostic.spec.ts
- mon-aide-cyber-ui/test/domaine/diagnostic/reducteurReponse.spec.ts
- mon-aide-cyber-ui/test/tsconfig.test.json
**Contexte**
Les réponses données lors d'un diagnostic sont dupliquées dans Metabase.
**Description**
Lorsque l'on change de thématique dans un diagnostic ou que l'on clique sur `Terminer Diagnostic`, les résultats des réponses envoyés sur Metabase sont dupliquées (voir la capture ci-dessous).
**Comment reproduire**
- Vider la table `diagnostics` dans MAC
- Vider la table `evenements` dans MAC journal
- Ouvrir les outils développeurs du navigateur dans l'onglet réseau
- Ouvrir une page de Metabase en allant dans la vue des événements (constater qu'il n'y en a aucun)
- Lancer un diagnostic
- Répondre à différentes questions et constater que les appels pour chaque réponse sont faits dans la console développeur
- Ouvrir la page Metabase et constater que les événements sont présents
- Vider …
> [CORRECTION] Corrige l'envoi des réponses déjà données lorsque l'on change de thématique

- mon-aide-cyber-ui/src/composants/diagnostic/ComposantDiagnostic.tsx
- les réponses sous forme de liste prennent le premier élément comme sélectionné et il n'est pas possible de le sélectionné par la suite
- ajoute un libellé 'Sélectionnez une option'
> [CORRECTION] Corrige la gestion des réponses sous forme de liste

- mon-aide-cyber-api/src/diagnostic/recommandations/recommandationsSecuriteInfrastructure.ts
- mon-aide-cyber-api/src/infrastructure/pdf/modeles/recommandations/infras/securite-infrastructure-mises-a-jour-fonctionnelles-securite-equipements-securite-deployees-niveau2-comment.pug
- mon-aide-cyber-api/src/infrastructure/pdf/modeles/recommandations/infras/securite-infrastructure-mises-a-jour-fonctionnelles-securite-equipements-securite-deployees-niveau2-pourquoi.pug
Dans la thématique **Sécurité des infrastructures**, la question `Les mises à jour fonctionnelles et de sécurité des équipements de sécurité sont-elles déployées ?` n’a pas de **niveau 2**. 
Elle prenait jusqu’alors la recommandation de **niveau 2** de la question `Les mises à jour fonctionnelles et de sécurité des systèmes d'exploitation des serveurs, services et logiciels d'admnistration sont-elles déployées ?`.
**La recommandation a été remplacée par celle de niveau 1 pour la question correspondante.**
> [CORRECTION] Corrige la recommandation sur les mises à jour de sécurité des équipements

- mon-aide-cyber-api/src/adaptateurs/AdaptateurDeVerificationDeSessionHttp.ts
- package-lock.json
- package.json
Par exemple, le cas ci-dessous n'était pas pris en compte et renvoyait un 403 lorsqu'un aidant accédait à une ressource protégée. 
` session=ey...9; org.cups.sid=a...8; session.sig=i...M`
Plutôt que d'améliorer la regex, j'ai directement utilisé la bibliothèque 'Cookies' dont 'cookie-session' est déjà dépendante.
> [CORRECTION][AUTHENTIFICATION] permet le parsing du cookie de session dans le cas où il y a d'autres cookies présent

- mon-aide-cyber-api/src/api/representateurs/types.ts
Ce champs est inutilisé et est incohérent avec le modèle
> [REMANIEMENT] Supprime le champs reponses du modèle ReponseATranscrire

- mon-aide-cyber-api/src/diagnostic/MoteurIndice.ts
- mon-aide-cyber-api/test/diagnostic/MoteurIndice.spec.ts
**Contexte**
La génération de la restitution ne fonctionne pas.
- Lancer un diagnostic
- Se rendre sur la thématique `Réaction`
- Répondre à la question `Des sauvegardes régulières des données et des systèmes d'information sont-elles réalisées ?` par `Des sauvegardes des données et des systèmes d'information sont réalisées ponctuellement.` ou `Des sauvegardes des données et des systèmes sont réalisées de manière automatique et régulière`
- Répondre par `Je ne sais pas` ou `Non applicable` indifféremment (voir capture d'écran)
- Cliquer sur `Terminer Diagnostic`
La génération de la restitution ne fonctionne pas.
Le message suivant apparaît: `{"message":"MonAideCyber n'est pas en mesure de traiter votre demande."}`
La restitution …
> [CORRECTION][RESTITUTION] Corrige le calcul des indicateurs lorsqu'une question tiroir n'a pas de résultat

- mon-aide-cyber-ui/src/assets/styles/_diagnostic.scss
**Contexte:**
Affichage du diagnostic
**Description:**
Lorsque l'on scroll vers le bas d'une thématique dans le diagnostic, la barre de navigation se cache derrière le header du diagnostic.
**Reproduction:**
1. Se rendre sur un diagnostic ou en lancer un nouveau
2. Descendre au bas d'une thématique
**Résultat constaté:**
Les premières thématiques sont masquées par le header du diagnostic (cf capture ci-dessous)
**Résultat attendu:**
La barre de navigation et l'intégralité des thématiques doit être accessible où que l'on soit dans la page.
> [CORRECTION][DIAGNOSTIC] Corrige l'apparence de la barre de navigation dans le diagnostic

- mon-aide-cyber-api/src/adaptateurs/AdaptateurDeVerificationDeSession.ts
- mon-aide-cyber-api/src/adaptateurs/AdaptateurDeVerificationDeSessionHttp.ts
- mon-aide-cyber-api/src/api/routesAPIDiagnostic.ts
- mon-aide-cyber-api/src/api/routesAPIDiagnostics.ts
- mon-aide-cyber-api/test/adaptateurs/AdaptateurDeVerificationDeSessionDeTest.ts
- mon-aide-cyber-api/test/adaptateurs/AdaptateurDeVerificationDeSessionHttp.spec.ts
Cette PR propose de remplacer `AdaptateurDeVerificationDeSession.verifie` par une approche plus orientée middleware express.
Exemple sur une route :
```js
routes.post(
'/',
(requete, reponse, suite) =>
configuration.adaptateurDeVerificationDeSession.verifie(
'Lance le diagnostic',
requete,
reponse,
suite,
),
(_requete: Request, reponse: Response, suite: NextFunction) => {
…
}
}
```
```js
routes.post(
'/',
session.verifie('Lance le diagnostic'),
(_requete: Request, reponse: Response, suite: NextFunction) => {
…
}
}
```
-  `verifieParMiddleware` typé comme un `RequestHandler` : ça veut dire qu'il est un middleware qui renvoie la fonction « suivante »
- `verifieParMiddleware` appelé sans passer `requete, reponse, suite` grâce au design expliqué ci-dessus
⚠️ Prettier a modifié des guillemets …
> 💡 [REMANIEMENT] Propose une vérification de session par `middleware`

- mon-aide-cyber-api/src/api/routesAPIUtilisateur.ts
- mon-aide-cyber-api/src/compte/ServiceFinalisationCompte.ts
- mon-aide-cyber-api/test/api/routesAPIUtilisateur.spec.ts
- mon-aide-cyber-api/test/compte/ServiceFinalisationCompte.spec.ts
- On ne renvoie pas d'erreur si on reçoit une demande de finalisation pour un aidant ayant déjà finalisé son compte
- On ne modifie pas les dates de signature dans le cas ci-dessus
> [CORRECTION] Corrige le nom des champs exposés sur l'API et prends en compte les retours post PR

- mon-aide-cyber-api/package.json
- mon-aide-cyber-ui/package.json
- package-lock.json
Corrige la [vulnérabilité](https://github.com/betagouv/mon-aide-cyber/security/dependabot/17) détectée par dependabot.
- Vite: `4.5.2` -> `5.0.12`
- Vitest: `0.32.2` -> `1.2.2`
> Actualisation de la version de vite et vitest

- mon-aide-cyber-ui/package.json
- package-lock.json
Met à jour les dépendances de Storybook pour corriger la [faille de sécurité](https://github.com/betagouv/mon-aide-cyber/security/dependabot/20) lié au package `ip`.
> [CORRECTION] Actualisation dépendance Storybook

- mon-aide-cyber-ui/src/composants/diagnostic/ComposantRestitution.tsx
> [REMANIEMENT] ressource cybermalveillance.gouv.fr

- mon-aide-cyber-api/src/adaptateurs/AdaptateurDeVerificationDeSessionHttp.ts
- mon-aide-cyber-api/test/adaptateurs/AdaptateurDeVerificationDeSessionHttp.spec.ts
**Contexte**
La vérification des cookies au niveau de MAC produit des erreurs.
- Se connecter à MAC
- Vider ses cookies dans la console de développement du navigateur
- Rafraîchir la page
- Le message suivant s'affiche
- Nous recevons une alerte sur Sentry
- Une trace apparaît dans les logs de MAC
- Une erreur 500 est renvoyée par le serveur
- Devrait afficher un message à l'utilisateur disant que l'accès à la page demandée est interdit
- L'erreur remontée au niveau de Sentry doit être gérée
- MAC doit retourner une erreur HTTP 403
> [CORRECTION] Corrige l'erreur 500 remontée par MAC lors de la vérification des cookies

- mon-aide-cyber-ui/src/Accueil.tsx
- mon-aide-cyber-ui/src/assets/styles/_footer.scss
- mon-aide-cyber-ui/src/assets/styles/index.mobile-paysage.scss
- mon-aide-cyber-ui/src/assets/styles/index.scss
Corrige l'affichage des éléments :
- tuiles du hero
- mots du directeur
- taille texte
- taille guillemets
- padding des tuiles "participer"
- softwrap du titre "qu'est-ce que MAC"
> [ACCUEIL][MOBILE] adapte l'affichage quand le mobile est en mode paysage

- mon-aide-cyber-api/src/infrastructure/adaptateurs/transcripteur/transcripteurSecuritePoste.ts
**Contexte**
Présentation de la question `Si entité à risque d'espionnage, les disques durs des matériels nomades sont-ils chiffrés ?` dans la thématique sur la sécurité des postes.
- Lancer un diagnostic
- Se rendre sur la thématique `Sécurité des postes`
- Descendre jusqu'à la question 24
Les questions `Un outil complémentaire à un antivirus de type EDR a-t-il été mis en place ?` et `Si entité à risque d'espionnage, les disques durs des matériels nomades sont-ils chiffrés ?` sont regroupées (voir capture).
Les 2 questions ne font pas partie du même groupe, la question `Si entité à risque d'espionnage, les disques durs des matériels nomades sont-ils chiffrés ?` est une question à part entière
> [DIAGNOSTIC] Corrige la manière dont est présentée la question sur les disques durs des matériels nomades

- mon-aide-cyber-ui/src/assets/styles/_menu-utilisateur.scss
**Menu utilisateur**
- Se connecter à MAC
- Cliquer sur le menu utilisateur
- Cliquer sur la partie gauche du bouton déconnecter (le bandeau devrait se mettre en sur-brillance, cf capture)
L'utilisateur n'est pas déconnecté, il est redirigé vers la page d'accueil.
L'utilisateur est déconnecté
> [CORRECTION] Corrige le focus sur Me Déconnecter dans le menu utilisateur

- mon-aide-cyber-ui/src/composants/utilisateur/ComposantMenuUtilisateur.tsx
Afin d'éliminer le décallage entre le lien pour se connecter et l'affichage du menu à la connexion
> [CORRECTION] Corrige le remplissage à droite du menu utilisateur.

- mon-aide-cyber-ui/src/composants/intercepteurs/ComposantIntercepteur.tsx
- mon-aide-cyber-ui/src/main.tsx
**Contexte**
Gestion des erreurs React dans le front
- se connecter avec un compte (avec ou sans espace)
- une fois connecté, allé sur la page /cgu ou charte-aidant
la page s’affiche correctement
la page reste blanche, la console développeur affiche une erreur
PI : En positionnant le ErrorBoundary au plus haut dans l'arbre React (main.tsx) l’erreur disparaît
> [CORRECTION] Corrige l’affichage des erreurs qui en cas de navigation empêche l’affichage des pages publiques

- mon-aide-cyber-ui/src/composants/diagnostic/ComposantLancerDiagnostic.tsx
- mon-aide-cyber-ui/src/composants/espace-aidant/tableau-de-bord/ComposantDiagnostics.tsx
Lorsque l’on est sur la page **Mes diagnostics** , on peut lancer un diagnostic en cliquant à côté du bouton `Lancer un diagnostic`.
- Se connecter à son espace Aidant
- Cliquer sur la ligne à côté du bouton Lancer un diagnostic (cf capture ci-dessous)
Un diagnostic est lancé, on se retrouve sur la page d’un nouveau diagnostic
Cliquer en dehors du bouton ne doit pas lancer un nouveau diagnostic
> [CORRECTION] Corrige le bouton et le lien pour lancer un diagnostic

- mon-aide-cyber-api/src/diagnostic/Diagnostic.ts
- mon-aide-cyber-api/test/diagnostic/Diagnostic.spec.ts
Les 8 mesures les plus prioritaires (dont la priorisation est maximum 8) sont prises en compte dans la génération des mesures quelque soit leur niveau comparé aux mesures moins prioritaires.
Si un Aidé a répondu à une question, ayant une priorité entre 1 et 8, donnant lieu à une mesure de niveau 2, la mesure de niveau 2 est remontée dans les mesures priorisées (prioritaires ou autres mesures) avant toutes les mesures des questions ayant une priorité entre 9 et 34 (quelque soit le niveau de la mesure).
**Question A :**
- priorité 1
- réponses :
- Oui
- Non (niveau 1)
- En cours (niveau 2)
**Question B :**
- priorité 2
- réponses :
- Oui
- Non (niveau 1)
- En cours (niveau 2)
**Question C :**
- priorité 11
- réponses :
- Oui (niveau 2)
- Non (niveau 1)
‌
**Les réponses fournies par l’Aidé …
> [RESTITUTION] Ajoute la nouvelle règle de génération des mesures

- mon-aide-cyber-api/src/diagnostic/referentiel/donneesSecuritePoste.ts
- mon-aide-cyber-api/test/diagnostic/coherenceDiagnostic.spec.ts
Lors d'un diagnostic et de l'accès à la restitution.
À la question "25. En complément de l'antivirus, un outil de type EDR a-t-il été mis en place ?"
Répondre 'Oui, un outil de type EDR a été mis en place et ses alertes sont systématiquement traitées'
La restitution est faussé puisque la mesure "Traiter systématiquement les alertes générées par l'EDR" est proposé.
La mesure  "Traiter systématiquement les alertes générées par l'EDR" ne doit pas s'afficher lorsque la réponse 'Oui, un outil de type EDR a été mis en place et ses alertes sont systématiquement traitées' est cochée.
> [CORRECTION] Modifie l’identifiant de la réponse à la question sur les EDR

- mon-aide-cyber-api/src/infrastructure/bus/BusEvenementMAC.ts
Import des Aidants
- Prendre un fichier d’Aidants à importer
- Importer les Aidants
- Constater que les comptes utilisateurs ont bien été créés
- Vérifier le nombre d’événements `AIDANT_CREE` dans Metabase
Le nombre d’événements `AIDANT_CREE` dans Metabase ne correspond pas au nombre de comptes Aidants réellement créés
**Exécution de l’import d’Aidants**
**Aidants créés dans MAC**
**Nombre d’événements `AIDANT_CREE` dans Metabase**
Le nombre d’événements `AIDANT_CREE` dans Metabase doit correspondre aux nombre de comptes effectivement créés.
> [CORRECTION] Corrige le problème de traitement asynchrone lors de la consommation d’événements par le bus d’événements

- mon-aide-cyber-api/src/diagnostic/referentiel/donneesSecuriteAcces.ts
Accorder protégés en protégées
> [CORRECTION][DIAGNOSTIC] Corrige la faute de grammaire sur les réponses à la question sur les accès distants aux systèmes industriels

- mon-aide-cyber-api/src/diagnostic/mesures/mesuresSecuriteAcces.ts
- mon-aide-cyber-api/src/diagnostic/mesures/mesuresSensibilisation.ts
- mesure de niveau 1 'acces-utilisateurs-administrateurs-poste'
- mesure de niveau 1 'sensibilisation-actions-sensibilisation-menace-et-bonnes-pratiques'
- mesure de niveau 1 'sensibilisation-collaborateurs-soumis-obligations-usages-securises'
> [CORRECTION][REFERENTIEL] Retire des '.' dans les titres des mesures ci-dessous :

- mon-aide-cyber-api/src/diagnostic/Diagnostic.ts
- mon-aide-cyber-api/src/diagnostic/ServiceDiagnostic.ts
- mon-aide-cyber-api/src/espace-aidant/tableau-de-bord/ServiceTableauDeBord.ts
- mon-aide-cyber-api/src/infrastructure/entrepots/memoire/EntrepotMemoire.ts
- mon-aide-cyber-api/src/infrastructure/entrepots/postgres/EntrepotDiagnosticPostgres.ts
- mon-aide-cyber-api/test/diagnostic/ServiceDiagnostic.spec.ts
- mon-aide-cyber-api/test/diagnostic/ServiceDiagnosticTest.ts
- mon-aide-cyber-api/test/infrastructure/entrepots/postgres/EntrepotDiagnosticPostgres.spec.ts
**Contexte**
Tableau de bord Aidant
**Description**
Une alerte [Sentry](https://sentry.incubateur.net/organizations/betagouv/issues/108102/?project=125&referrer=webhooks_plugin) est remontée lorsque l’on charge le TDB. Il s’agit d’une erreur SELECT N+1.
- Configurer Sentry sur son environnement de développement || Faire le test en démo
- Se connecter à son espace Aidant
Une erreur Sentry est levée (Sur Mattermost et dans Sentry)
Plus aucune erreur du type `SELECT N+1` n’est remontée sur Sentry et dans Mattermost
**NB :**
Techniquement, nous récupérons la liste des identifiants des diagnostics de l’Aidant puis nous bouclons sur chacun d’entre eux afin de faire la requête vers le diagnostic correspondant.
Une requête du type …
> [CORRECTION][TABLEAU DE BORD] Corrige la manière dont est récupéré le contexte des diagnostics

- mon-aide-cyber-ui/src/composants/diagnostic/ComposantLancerDiagnostic.tsx
- mon-aide-cyber-ui/src/composants/diagnostic/ComposantRestitution/useComposantRestitution.ts
- mon-aide-cyber-ui/src/domaine/Lien.ts
- mon-aide-cyber-ui/src/domaine/LienRoutage.ts
**Contexte**
Lancer un diagnostic
**Description**
Lorsque l’on veut commencer un diagnostic, une page blanche s’affiche en lieu et place du diagnostic
- Se connecter à son espace Aidant
- Cliquer sur le bouton `Créer un diagnostic`
- Valider la modale et cliquer sur `Commencer le diagnostic`
Le diagnostic est vide 
Le diagnostic est affiché
**NB :**
Cette erreur est due à un remaniement que l’on a fait et qui a été mal testé. 
La correction apportée va empêcher le rafraîchissement de la page. Une correction sera apportée ultérieurement lorsque nous ferons évoluer le moteur HATEOAS
> [CORRECTION][DIAGNOSTIC] Corrige le lancement du diagnostic qui ne s’affichait plus

- mon-aide-cyber-api/src/infrastructure/restitution/html/modeles/graphe-polaire.pug
**Contexte**
Affichage des indicateurs lors de la restitution.
- Initier un diagnostic
- Répondre aux questions de toutes les thématiques
- Cliquer sur `Accéder à la restitution`
Les éléments de chaque indicateurs sont trop rapprochés les uns des autres ce qui pose des problèmes d’accessibilité
Les éléments de chaque indicateurs doivent être séparés par une bordure pour facilité l’accessibilité
> [CORRECTION][INDICATEURS] Ajoute un traite entre chaque indicateur du graphe polaire

- mon-aide-cyber-api/src/annuaire-aidants/ServiceAnnuaireAidants.ts
- mon-aide-cyber-api/test/annuaire-aidants/ServiceAnnuaireAidants.spec.ts
**Contexte**
Annuaire des Aidants.
Lorsque l’on se rend sur l’annuaire des Aidants, l’annuaire ne se charge pas.
- Créer un Aidant avec juste un prénom
- Se rendre sur l’annuaire
La page affiche chargement des Aidants
Les logs applicatifs affichent 
```
2024-10-18 16:24:12.876126472 +0200 CEST[web-1] TypeError: Cannot read properties of undefined (reading '0')
2024-10-18 16:24:12.876127270 +0200 CEST[web-1] at ServiceAnnuaireAidants.formateLeNom (/app/mon-aide-cyber-api/src/annuaire-aidants/ServiceAnnuaireAidants.ts:12:28)
2024-10-18 16:24:12.876127730 +0200 CEST[web-1] at /app/mon-aide-cyber-api/src/annuaire-aidants/ServiceAnnuaireAidants.ts:23:27
2024-10-18 16:24:12.876128627 +0200 CEST[web-1] at …
```
> [CORRECTION][ANNUAIRE AIDANTS] Corrige le formatage du nom de l’Aidant

- mon-aide-cyber-api/src/api/demandes/routeAPIDemandeDevenirAidant.ts
- mon-aide-cyber-api/test/api/demandes/routeAPIDemandeDevenirAidant.spec.ts
**Contexte**
Demande devenir Aidant
- Faire une demande devenir aidant en remplissant le champ mail avec des majuscules (e.g : `Jean.DupOnT@mail.com`)
- Finaliser la demande en envoyant le mail de création de l’espace Aidant (`npm run -w mon-aide-cyber-api administration:envoi-mail-creation-compte-aidant -- jean.dupont@mail.com` ),
Une erreur est remontée disant que la demande n’existe pas
**Comportement attendu**
S'assurer en base de données que dans demande Devenir Aidant, si l'email est saisi avec des majuscules, il sera stocké en minuscules dans tous les cas.
**Problème actuel**
Lorsque l'on fait une demande Devenir Aidant, si le mail comporte des majuscules, celles-ci ne sont pas transformées en minuscule. Cela a pour conséquence de ne pas …
> [CORRECTION][DEMANDE DEVENIR AIDANT] Corrige la saisie du mail de la demande en la mettant en minuscule

- mon-aide-cyber-api/src/aide/CapteurCommandeCreerAide.ts
- mon-aide-cyber-api/src/api/demandes/routesAPIDemandeSolliciterAide.ts
- mon-aide-cyber-api/src/gestion-demandes/aide/CapteurSagaDemandeSolliciterAide.ts
- mon-aide-cyber-api/src/gestion-demandes/aide/adaptateurCorpsMessage.ts
- mon-aide-cyber-api/test/api/demandes/routesAPIDemandeSolliciterAide.spec.ts
- mon-aide-cyber-api/test/gestion-demandes/aide/CapteurSagaDemandeSolliciterAide.spec.ts
- Rendre le lien vers le mail cliquable en ajoutant l'objet du mail `[MonAideCyber] Indisponibilité réalisation diagnostic dans le département DEPARTEMENT`
- Suppression du mail `monaidecyber@ssi.gouv.fr` dans la signature
> [CORRECTION][ANNUAIRE AIDANTS][MISE EN RELATION] Applique les retours sur le corps du mail à l'Aidant

- mon-aide-cyber-api/src/api/annuaire-aidants/routeAPIAnnuaireAidants.ts
- mon-aide-cyber-api/test/annuaire-aidants/constructeurAidant.ts
- mon-aide-cyber-api/test/api/annuaire-aidants/routeAPIAnnuaireAidants.spec.ts
- mon-aide-cyber-ui/src/domaine/vitrine/ecran-annuaire/composants/liste-aidants/useListeAidants.ts
**Contexte**
Annuaire des Aidants
- Se rendre sur l'annuaire des Aidants
- Ouvrir la console développeur, onglet réseau
- Sélectionner la collectivité Wallis & Futuna
‌- Il n'y a pas d'Aidants remontés 
- L'appel réseau remonte en erreur
- L'appel réseau ne remonte pas en erreur
- Les Aidants et Wallis & Futuna sont retournés
**NB**
- Il faut faire de l'URL encode codé front mais aussi côté back dans la réponse hateoas
> [CORRECTION][ANNUAIRE AIDANTS] Corrige l'appel à l'annuaire lorsque l'on choisit la Collectivité de Wallis & Futuna

- mon-aide-cyber-ui/.env-template
- mon-aide-cyber-ui/src/assets/styles/_maintenance.scss
- mon-aide-cyber-ui/src/assets/styles/index.scss
- mon-aide-cyber-ui/src/composants/alertes/BandeauMaintenance.tsx
- mon-aide-cyber-ui/src/composants/layout/Header.tsx
- mon-aide-cyber-ui/src/composants/layout/HeaderAidant.tsx
Cette PR permet de prévenir d'une maintenance à venir via un bandeau 👇 
⚠️  Le bandeau est commandé par une variable `VITE_` qui est donc une variable « build time ».
Afficher ou supprimer le bandeau nécessite donc un re-build du front.
Ce n'est pas idéal, mais c'est suffisant pour le peu de fois où ce sera utilisé.
⚠️ Je n'ai pas testé l'affichage dans l'espace aidant. Si vous pouvez tester de votre côté ça serait top.
📋 La suite sera de faire une PR qui sert une page complète de maintenance lorsque la maintenance est indiquée comme « ACTIVE » par une variable d'env.
> [MODE MAINTENANCE] Affiche un bandeau de maintenance si nécessaire

- mon-aide-cyber-api/.env.template
- mon-aide-cyber-api/index.ts
- mon-aide-cyber-api/src/adaptateurs/adaptateurEnvironnement.ts
- mon-aide-cyber-api/src/maintenance/maintenance.html
- mon-aide-cyber-api/src/serveur.ts
- mon-aide-cyber-api/test/api/testeurIntegration.ts
Cette PR permet de passer la totalité de MAC en mode maintenance si `process.env.MAINTENANCE_EST_ACTIVE` vaut `true`.
La seule page servie devient 👇 
Le créneau « aujourd'hui de 12h à 14h » est hard-codé… Ça me semble suffisant pour notre besoin.
> [MAINTENANCE] Activation d'une page de maintenance côté serveur

- mon-aide-cyber-api/src/api/routesAPIAuthentification.ts
- mon-aide-cyber-api/test/api/routesAPIAuthentification.spec.ts
**Contexte**
Déconnexion après s’être connecté via le formulaire de connexion MonAideCyber
- Se connecter via le formulaire de connexion
- Cliquer sur le bouton `Se déconnecter`
L’Aidant n’est pas déconnecté
L’Aidant est déconnecté
> [CORRECTION][CONNEXION] Permets de se déconnecter après s’être connecté via le formulaire MonAideCyber

- mon-aide-cyber-api/src/api/demandes/routeAPIDemandeDevenirAidant.ts
- mon-aide-cyber-api/test/api/demandes/routeAPIDemandeDevenirAidant.spec.ts
**Contexte**
Demande devenir Aidant
- Effectuer une demande devenir Aidan via un curl `curl 'http://localhost:8081/api/demandes/devenir-aidant' \
-H 'Accept: application/json' \
--data-raw '{"nom":"Nouveau parcours II","prenom":"Test","mail":"test-nouveau-parcours_02@yopmail.com","departement":"Inconnu","cguValidees":true}'`
- Une erreur est remontée
- La demande correspondante est persistée
- Une erreur est remontée
- Aucune demande correspondante n'est persistée
> [CORRECTION][DEMANDE DEVENIR AIDANT] Corrige la création d'une demande alors qu'une erreur a été remontée

- mon-aide-cyber-api/src/gestion-demandes/devenir-aidant/CapteurCommandeDevenirAidant.ts
- mon-aide-cyber-api/test/gestion-demandes/devenir-aidant/CapteurCommandeDevenirAidant.spec.ts
**Contexte**
Mise à jour d'une demande existante
- Faire une demande sur le parcours actuel [ici](http://localhost:8081/devenir-aidant)
- Modifier la variable d'environnement `DATE_NOUVEAU_PARCOURS_DEMANDE_DEVENIR_AIDANT` en la mettant à une date antérieure à la date du test
- Redémarrer le serveur MAC
- Se positionner sur la branche `parcours-devenir-aidant`
- Faire une nouvelle demande sur le nouveau parcours [ici](http://localhost:8081/demandes/devenir-aidant)
L'ancienne demande n'est pas mise à jour avec les informations du nouveau Parcours
L'ancienne demande est complétée avec les nouvelles informations et / ou celles modifiées
> [CORRECTION][PARCOURS DEVENIR AIDANT] Corrige la mise à jour d'une demande déjà existante

- mon-aide-cyber-api/src/infrastructure/entrepots/postgres/EntrepotUtilisateurMACPostgres.ts
- mon-aide-cyber-api/src/infrastructure/entrepots/postgres/EntrepotsMAC.ts
- mon-aide-cyber-api/test/infrastructure/entrepots/postgres/EntrepotsPostgres.spec.ts
- mon-aide-cyber-api/test/infrastructure/securite/ServiceDeChiffrementClair.ts
**Contexte**
Affichage du nom de l'Aidant / Utilisateur Inscrit dans l'entête de MAC
- Se connecter sur MAC
- Faire un rafraichissement de la page
Le nom apparaît avec des chiffres et des lettres 
Le nom est affiché correctement
**NB**
Il s'agit de l'affichage chiffré du nom de nos utilisateurs
> [CORRECTION][PARCOURS DEVENIR AIDANT] Corrige l'affichage du nom de l'Aidant dans l'entête

- mon-aide-cyber-api/test/ConsignateurErreurs.spec.ts
- mon-aide-cyber-api/test/api/aidant/routesAPIAidantPreferences.spec.ts
- mon-aide-cyber-api/test/api/aidant/routesAPIProfil.spec.ts
- mon-aide-cyber-api/test/api/annuaire-aidants/routeAPIAnnuaireAidants.spec.ts
- mon-aide-cyber-api/test/api/auto-diagnostic/routesAPIDiagnosticLibreAcces.spec.ts
- mon-aide-cyber-api/test/api/demandes/routeAPIDemandeDevenirAidant.spec.ts
- mon-aide-cyber-api/test/api/demandes/routesAPIDemandeEtreAide.spec.ts
- mon-aide-cyber-api/test/api/demandes/routesAPIDemandeSolliciterAide.spec.ts
- mon-aide-cyber-api/test/api/executeurRequete.ts
- mon-aide-cyber-api/test/api/pro-connect/routeProConnect.spec.ts
- mon-aide-cyber-api/test/api/recherche-entreprise/routesAPIRechercheEntreprise.spec.ts
- mon-aide-cyber-api/test/api/routeAPIContexte.spec.ts
- mon-aide-cyber-api/test/api/routeContact.spec.ts
- mon-aide-cyber-api/test/api/routesAPIAuthentification.spec.ts
- mon-aide-cyber-api/test/api/routesAPIDiagnostic.spec.ts
- mon-aide-cyber-api/test/api/routesAPIUtilisateur.spec.ts
- mon-aide-cyber-api/test/api/statistiques/routesStatistiques.spec.ts
- mon-aide-cyber-api/test/api/tableau-de-bord/routesAPITableauDeBord.spec.ts
- mon-aide-cyber-api/test/api/testeurIntegration.ts
- Les tests échouaient de manière aléatoire malgré la génération aléatoire d'un nombre compris entre 10_000 et 20_000
- La configuration du port express à 0 a comme effet de rechercher le premier port libre
> [CORRECTION][TESTS] Corrige les échecs aléatoires EADDRINUSE:

- mon-aide-cyber-ui/src/vues/CharteAidant.tsx
Contexte
Affichage de la charte Aidant web. Depuis les derniers changements du 31 Janvier 2025, la charte comporte l'encart de signature et de mention Lu et approuvé à la fin du contenu. Cette zone n'est destinée qu'au fichier PDF.
Reproduction
Accéder à la page web de la charte de l'Aidant.
Résultat attendu
La zone de signature PDF n'est plus présente
> [CORRECTION][CHARTE AIDANT] Retire les mentions Lu et approuvé en bas de charte WEB

- mon-aide-cyber-api/src/api/routesAPIUtilisateur.ts
- mon-aide-cyber-api/src/espace-aidant/Aidant.ts
- mon-aide-cyber-api/src/espace-aidant/ServiceAidant.ts
- mon-aide-cyber-api/src/espace-aidant/ServiceAidantMAC.ts
- mon-aide-cyber-api/src/espace-aidant/adaptateurCorpsMessage.ts
- mon-aide-cyber-api/test/api/routesAPIUtilisateur.spec.ts
- mon-aide-cyber-api/test/espace-aidant/ServiceAidantMAC.spec.ts
Cas : 
-> Un Aidant se connecte pour la première fois depuis le 31 Janvier. 
-> L'outil lui demande de sélectionner son choix d'utilisation de l'outil
-> L'utilisateur choisit de rester Aidant
-> Au moment de choisir le type d'Aidant, l'utilisateur se rend compte qu'il n'adhère pas encore à une association
-> Il sélectionne donc le dernier choix (cf: capture d'écran ci-dessous)
-> L'utilisateur clique sur le bouton "Suivant"
-> Il valide la Charte de l'Aidant ainsi que les nouvelles CGU
-> Au moment de cliquer sur le bouton "Suivant", dont le rôle est de valider le profil de l'Aidant, il ne se passe rien
Ci-dessous, des captures d'écran descriptives de l'erreur (vues lors d'une visio avec une Aidante)
> [CORRECTION][TRI DES AIDANTS] Rends l'entité optionnelle si l'utilisateur choisit une Association ou qu'il est en attente d'adhésion

- mon-aide-cyber-api/src/infrastructure/entrepots/postgres/EntrepotStatistiquesPostgres.ts
- mon-aide-cyber-api/test/infrastructure/entrepots/postgres/EntrepotsPostgres.spec.ts
**Contexte**
Statistiques publiques
- Se rendre sur la page des statistiques publiques
- La statistique `Aidants Cyber référencés` remonte tous les utilisateurs quelque soit leur profil
**Résultat constaté** 
- Il y a environ 220 Utilisateurs inscrits comptabilisés dans la statistique
- Les Utilisateurs inscrits ne doivent pas être remontés dans les status
> [CORRECTION][STATISTIQUES] Corrige le nombre d’Aidants retourné dans les statistiques publiques

- mon-aide-cyber-api/src/api/hateoas/contextesUtilisateur.ts
- mon-aide-cyber-api/test/api/aidant/routesAPIProfil.spec.ts
- mon-aide-cyber-api/test/api/routesAPIUtilisateur.spec.ts
**Contexte**
Connexion via ProConnect pour la première fois pour un Utilisateur Inscrit
- Pré-requis : utiliser un compte ProConnect dont l’utilisateur n’est pas encore connu par MAC 
- Ouvrir les outils développeur du navigateur, onglet réseau
- Se connecter avec ProConnect 
- Le lien `Kit de communication des Aidants` est disponible dans le menu de navigation gauche de l’espace Utilisateur
- HATEOAS ne remonte pas l’action `demande-devenir-aidant`
- Le lien `Kit de communication des Aidants` n’est pas visible dans le menu de navigation gauche de l’espace Utilisateur
- Un lien `Devenir Aidant` est visible dans le menu de navigation gauche de l’espace Utilisateur
- HATEOAS ne remonte pas l’action `demande-devenir-aidant`
> [CORRECTION][MON ESPACE] Masque le lien vers le kit des Aidants pour un utilisateur inscrit qui se connecte pour la première fois.

- mon-aide-cyber-ui/src/composants/auto-completion/AutoCompletion.tsx
Comportement observé en démo :
Les suggestions déjà tapées par le client s'affichent par dessus la liste des résultats.
Attendu : 
Pas de suggestions navigateur pour ne pas gâcher la vue du client sur les résultats de l'autocomplétion.
> [CORRECTION][COMPOSANT AUTOCOMPLETION] Masque l'autocomplétion du navigateur client lors du click pour déplier les éléments

- docker-compose.yml
- mon-aide-cyber-api/src/gestion-demandes/aide/CapteurCommandeCreerDemandeAide.ts
- mon-aide-cyber-api/src/gestion-demandes/aide/CapteurSagaDemandeAide.ts
- mon-aide-cyber-api/src/infrastructure/entrepots/memoire/EntrepotMemoire.ts
- mon-aide-cyber-api/test/gestion-demandes/aide/CapteurSagaDemandeAide.spec.ts
- mon-aide-cyber-api/test/gestion-demandes/aide/ConstructeurDemandeAide.ts
- Pour lesquelles nous n’obtenons pas les métadonnées depuis Brevo :
- Une nouvelle demande d’Aide est crée
- Le contact Brevo est mis à jour avec les métadonnées manquantes
- Les mails restent les mêmes que ceux d’une demande d’Aide originale
Cela a un impacte au niveau communication car des mails sont envoyés aux COT, à MAC pouvant faire penser à une demande d’Aide initiale à affecter :
```
Bonjour,
Votre demande pour bénéficier de MonAideCyber a été prise en compte.
Un Aidant de proximité vous contactera sur l’adresse email que vous nous avez communiquée dans les meilleurs délais.
Voici les informations que vous avez renseignées :
- Signature des CGU le 04.03.2025 à 15:19
- Département : Gironde
- Raison sociale : OKIWI
Toute l’équipe reste à votre disposition,
L'équipe MonAideCyber …
```
> [DEMANDE AIDE] Gère les demandes d’aides incomplètes

- README.md
Suite à la session de pair prog' avec @CadiChris, nous avons rajouté la commande docker à exécuter pour avoir la base de données de tests en local.
> [README] Rajoute la commande à exécuter pour obtenir la base de données de tests

- mon-aide-cyber-api/src/api/associations/referentiel.yaml
> [RELAIS ASSOCIATIFS] Supprime les relais Campus Cyber de Toulon et Sophia pointant vers les universités correspondantes

- mon-aide-cyber-api/.env.template
- mon-aide-cyber-api/package.json
- mon-aide-cyber-api/src/adaptateurs/adaptateurEnvironnement.ts
- mon-aide-cyber-api/src/api/gestionnaires/erreurs.ts
- mon-aide-cyber-api/src/infrastructure/securite/Reseau.ts
- mon-aide-cyber-api/src/serveur.ts
- package-lock.json
Filtre les IP qui ont le droit d'accéder à MAC 
On permet au serveur de filtrer les IPs qui ont le droit d'effectuer des requêtes.
Si le paramètre n'est pas positionné, aucun filtrage n'a lieu. Si le paramètre est positionné, on va vérifié que la dernière IP forwarded for, positionnée par le reverse proxy, est bien autorisée à accéder au service.
On adapte le gestionnaire d'erreur pour retourner 401 et terminer le traitement de la requête en cas de IpDeniedError.
> Filtrage ip

- mon-aide-cyber-ui/index.html
- La variable 'VITE_GOOGLE_SEARCH_CONSOLE_VERIFICATION' n'est pas valorisée si elle n'existe pas, le SHA du script change donc et les CSP ne passent plus. Du coup on crée cette variable et on met false comme valeur par défaut
> [CORRECTION] Corrige l'exécution du script

- mon-aide-cyber-ui/src/assets/styles/_commun.scss
- mon-aide-cyber-ui/src/assets/styles/_header.scss
- mon-aide-cyber-ui/src/composants/layout/Header.tsx
- mon-aide-cyber-ui/src/composants/utilisateur/ComposantMenuUtilisateur.tsx
**Contexte**
Affichage des pages publiques en mode connecté
- Se rendre sur MAC (pour les devs, le commit `90cd08eb87330891adbc3eb233f0c0f363f93cbb` a fait apparaître problème)
- Se connecter
- Se rendre sur la page d’accueil ou toute autre page publique de MAC
- Une page d’erreur est affichée sur toutes les pages publiques 
- L’espace Aidant / Utilisateur inscrit n’est pas impacté 
Les pages publique s’affichent correctement lorsque l’on est connecté
**NB**
Durant l’investigation @CadiChris et @firefly33 se sont rendus compte que la classe crr `fr-header__tools-links` avait un impact avec l’intégration du composant web de la suite cyber.
Le menu est redessiné lorsque l’utilisateur est connecté et qu’il se rend sur les pages …
> [CORRECTION][SUITE CYBER] Intégration suite cyber nouveau header

- mon-aide-cyber-api/.env.template
- mon-aide-cyber-api/src/adaptateurs/adaptateurEnvironnement.ts
- mon-aide-cyber-api/src/infrastructure/adaptateurs/AdaptateurGestionnaireErreursSentry.ts
… pour éviter d'en envoyer 100K+ par semaine depuis la PROD.
Actuellement, MAC envoie bcp de traces par semaine 👇 
ℹ️ J'ai déjà créé les variables d'env en DEMO et PROD.
> [SENTRY] Variabilise le pourcentage de traces envoyées vers Sentry

- docker-compose.yml
Avec l’ajout de MSC dans nos environnements de dev, il y a un conflit au niveau des ports utilisés par les applications. 
En effet, le container UI de MAC expose le port 3000, or ce dernier n’a pas la nécessité d’être exposé. 
On utilise ce container comme environnement de build automatisé (pour être ISO prod), les sources sont transpilées à la volée à chaque changement et distribuée dans le répertoire dist du serveur MAC
> [SOIN][TECH] Supprime l’exposition du port 3000 du container UI de MAC

- mon-aide-cyber-api/src/api/demandes/routesAPIDemandeEtreAide.ts
- mon-aide-cyber-api/src/gestion-demandes/aide/CapteurSagaDemandeAide.ts
- mon-aide-cyber-api/test/api/demandes/routesAPIDemandeEtreAide.spec.ts
Afin de rediriger la sollicitation via l’annuaire vers MSC et afin de préserver l’anonymat de nos Aidants, MAC est capable de fournir l’identifiant de l’Aidant et interpréter cette donnée lors de la demande
> [DEMANDE AIDE] Effectue une demande d’Aide en fournissant l’identifiant de l’Aidant

- mon-aide-cyber-ui/src/composants/diagnostic/ComposantLancerDiagnostic.tsx
- mon-aide-cyber-ui/src/domaine/gestion-demandes/etre-aide/EtreAide.ts
- mon-aide-cyber-ui/test/domaine/gestion-demandes/etre-aide/EtreAide.spec.ts
Supprime l’ancre dans le lien de la modale pour partager l’URL de demande d’Aide correspondant à l’Aidant
> [MISE EN RELATION] Modifie le nom du paramètre fourni dans l’URL de demande d’Aide

- mon-aide-cyber-api/package.json
- mon-aide-cyber-api/src/administration/journal/rattrapage/commande.ts
Avec la commande `npm run -w mon-aide-cyber-api administration:rattrapage-journalisation-excel-demo`
> [JOURNAL] Ajoute un script de rattrapage pour insérer des données correspondant aux diags Excel et aux diags de démo

- mon-aide-cyber-api/src/gestion-demandes/aide/adaptateursCorpsMessage.ts
- mon-aide-cyber-api/src/infrastructure/entrepots/postgres/EntrepotAidantPostgres.ts
- mon-aide-cyber-api/test/infrastructure/entrepots/postgres/EntrepotsPostgres.spec.ts
**Contexte**
Mise en relation, mail envoyé aux COTs.
- Effectuer une demande d’Aide pour une administration publique (le mapping fait en interne pour correspondre au secteur d’activité retourné par recherche entreprise donne `["Adiministration", "Tertiaire"]`)
- Vérifier le mail envoyé aux COTs (via Brevo)
Certains Aidants apparaissent en double dans le mail
Les Aidants n’apparaissent pas en double
> [CORRECTION][MISE EN RELATION] Retourne une seule ligne par Aidant lorsque l’on a plusieurs secteurs d’activité correspondant à une entité Aidée

- mon-aide-cyber-api/src/gestion-demandes/aide/MiseEnRelationParCriteres.ts
- mon-aide-cyber-api/src/gestion-demandes/aide/adaptateursCorpsMessage.ts
- mon-aide-cyber-api/src/gestion-demandes/aide/miseEnRelation.ts
- mon-aide-cyber-api/test/gestion-demandes/aide/ConstructeurAdaptateurDeCorpsDeMessage.ts
- mon-aide-cyber-api/test/gestion-demandes/aide/MiseEnRelationParCriteres.spec.ts
On s’assure qu’en cas de matching infructueux, i.e aucun Aidant n’est retourné par l’algo de matching, les COT sont informés qu’ils doivent eux même assigner un Aidant à cette demande.
> [MISE EN RELATION] Envoie un email au COT si aucun Aidant ne correspond à la demande d’Aide

- mon-aide-cyber-api/src/gestion-demandes/aide/CapteurSagaDemandeAide.ts
- mon-aide-cyber-api/src/gestion-demandes/aide/MiseEnRelationDirecteAidant.ts
- mon-aide-cyber-api/src/gestion-demandes/aide/MiseEnRelationParCriteres.ts
- mon-aide-cyber-api/src/gestion-demandes/aide/adaptateursCorpsMessage.ts
- mon-aide-cyber-api/src/gestion-demandes/aide/miseEnRelation.ts
- mon-aide-cyber-api/src/infrastructure/adaptateurs/fabriqueAnnuaireCOT.ts
- mon-aide-cyber-api/test/espace-aidant/ServiceAidantMAC.spec.ts
- mon-aide-cyber-api/test/gestion-demandes/aide/ConstructeurAdaptateurDeCorpsDeMessage.ts
- mon-aide-cyber-api/test/gestion-demandes/aide/MiseEnRelationDirecteAidant.spec.ts
- mon-aide-cyber-api/test/gestion-demandes/aide/MiseEnRelationParCriteres.spec.ts
Il existe une méthode d’envoi récapitulatif de demande d’Aide aux COTs. Cette méthode est utilisée dans la mise en relation directe Aidant et la mise en relation par critères. 
Elle prend donc des paramètres conditionnels ce qui n’ont pas lieu d’être, autant faire une fonction spécifique pour chaque cas.
> [REMANIEMENT][MISE EN RELATION] Extrais une fonction d’envoi de mail récapitulatif pour les COT spécifiquement pour la mise en relation directe

- mon-aide-cyber-api/src/api/aidant/miseEnRelation.ts
- mon-aide-cyber-api/src/api/aidant/routesAPIAidantRepondreAUneDemande.ts
- mon-aide-cyber-api/src/api/gestionnaires/erreurs.ts
- mon-aide-cyber-api/src/domaine/erreurMAC.ts
- mon-aide-cyber-api/src/gestion-demandes/aide/DemandeAide.ts
- mon-aide-cyber-api/src/gestion-demandes/aide/MiseEnRelationParCriteres.ts
- mon-aide-cyber-api/test/api/aidant/routesAPIAidantRepondreAUneDemande.spec.ts
- mon-aide-cyber-api/test/gestion-demandes/aide/ConstructeurDemandeAide.ts
- mon-aide-cyber-api/test/infrastructure/entrepots/postgres/EntrepotAideConcret.spec.ts
- mon-aide-cyber-ui/src/domaine/gestion-demandes/repondre-a-une-demande/EcranRepondreAUneDemande.tsx
- mon-aide-cyber-ui/src/domaine/gestion-demandes/repondre-a-une-demande/composants/RepondreALaDemande.tsx
Cette PR prend la valeur du `<token>` présent dans `http://localhost:8081/repondre-a-une-demande?token=<token>` comme la source de données permettant de recherche la demande sur laquelle l'Aidant va postuler.
On cesse donc d'hard-coder les bons et mauvais chemins, au profit d'appels réels vers nos services et dépôts.
> [POSTULER] Affichage réel des informations relatives au token de mise en relation utilisé

- mon-aide-cyber-api/src/api/aidant/routesAPIAidantRepondreAUneDemande.ts
- mon-aide-cyber-api/src/gestion-demandes/aide/CapteurCommandeAttribueDemandeAide.ts
- mon-aide-cyber-api/src/gestion-demandes/aide/MiseEnRelationParCriteres.ts
- mon-aide-cyber-api/test/api/aidant/routesAPIAidantRepondreAUneDemande.spec.ts
- mon-aide-cyber-api/test/gestion-demandes/aide/ConstructeurDemandeAide.ts
- mon-aide-cyber-api/test/gestion-demandes/aide/MiseEnRelationParCriteres.spec.ts
Cette PR rajoute l'identifiant de la demande dans le token de mise en relation car on va en avoir besoin au moment de postuler.
```diff
export type TonkenAttributionDemandeAide = {
emailDemande: string;
+ identifiantDemande: crypto.UUID;
identifiantAidant: crypto.UUID;
};
```
> Rajout de l'identifiant de la demande dans le token de mise en relation

- mon-aide-cyber-api/src/adaptateurs/AdaptateurEnvoiMail.ts
- mon-aide-cyber-api/src/api/aidant/routesAPIAidantRepondreAUneDemande.ts
- mon-aide-cyber-api/src/gestion-demandes/aide/CapteurCommandeAttribueDemandeAide.ts
- mon-aide-cyber-api/src/gestion-demandes/aide/CapteurSagaDemandeAide.ts
- mon-aide-cyber-api/src/infrastructure/adaptateurs/AdaptateurEnvoiMailBrevo.ts
- mon-aide-cyber-api/src/infrastructure/adaptateurs/AdaptateurEnvoiMailMemoire.ts
- mon-aide-cyber-api/src/infrastructure/adaptateurs/adaptateurRechercheEntreprise.ts
- mon-aide-cyber-api/src/infrastructure/bus/BusCommandeMAC.ts
- mon-aide-cyber-api/test/api/aidant/routesAPIAidantRepondreAUneDemande.spec.ts
- mon-aide-cyber-api/test/gestion-demandes/aide/CapteurCommandeAttribueDemandeAide.spec.ts
Cette PR récupère réellement les informations de la demande et de l'Aidant pour l'envoi d'email de confirmation.
On cesse d'avoir des valeurs codées en dur.
On en profite pour refactorer les tests afin de réduire la duplication.
> [POSTULER] Place les informations liées à la demande / l'Aidant dans le mail de confirmation

- mon-aide-cyber-api/src/adaptateurs/adaptateurEnvironnement.ts
- mon-aide-cyber-api/src/gestion-demandes/aide/MiseEnRelationParCriteres.ts
- mon-aide-cyber-api/test/gestion-demandes/aide/MiseEnRelationParCriteres.spec.ts
Le bouchon mis en place avec les emails en dur afin de tester la cinématique est remplacé par les informations des vrais Aidants
Dès qu'on merge cette PR, on a une mise en relation qui est débouchonnée de part en part. Donc à merger en DERNIER.
> 🚨  [POSTULER] Envoie le mail pour postuler aux aidants qui matchent une demande d’Aide

- mon-aide-cyber-ui/index.html
- mon-aide-cyber-ui/package.json
- mon-aide-cyber-ui/src/Accueil.tsx
- mon-aide-cyber-ui/src/assets/styles/_centre-aide.scss
- mon-aide-cyber-ui/src/composants/layout/header/NavigationPublique.tsx
- package-lock.json
Cette PR a pour objectif de remplacer dans la landing page principale les deux éléments d'origine (Hero et carrousel) par les webcomponents de l'UI-KIT
> [BRIQUES REUTILISABLES UI-KIT] Intègre la brique Hero et le carrousel dans la page d'accueil de MAC

- mon-aide-cyber-api/src/adaptateurs/AdaptateurCmsCrispMAC.ts
Car l’adaptateur utilisé pour les tests utilise une dépendance de test qui n’est pas embarquée dans le build de production, du coup le déploiement échoue
> [CORRECTION] Utilise un adaptateur mémoire par défaut différent de celui des tests

- mon-aide-cyber-ui/src/domaine/crisp/article-crisp.scss
On veut que <ol start="3">, par exemple, soit pris en compte. Le DSFR fait un `counters()` personnalisé, qu'on ne veut pas : https://github.com/GouvernementFR/dsfr/blob/main/src/dsfr/core/style/typography/tool/_list.scss#L21
Ce qui donne un rendu correct 👇
> [CRISP] Corrige les reprises de compte des listes

- mon-aide-cyber-api/src/infrastructure/adaptateurs/AdaptateurEnvoiMailBrevo.ts
Afin que les COT tiennent à jour le suivi des demandes d’Aide
> [MISE EN RELATION] Ajoute le COT en copie du mail lorsqu’un Aidant a postulé à une demande d’Aide

- mon-aide-cyber-ui/src/domaine/crisp/article-crisp.scss
… car sinon la restitution de diag est impacté par le `body { overflow: hidden; }` lorsqu'une mesure prioritaire est dépliée.
Le bug se produisait sur la page de restitution : lorsqu'une mesure est dépliée le scroll devient inutilisable 👇 
Le but est de conserver un scroll désactivé sur les pages Crisp, lorsque le sommaire mobile est ouvert 👇
> [CORRECTION] Scope la règle CSS aux pages Crisp seulement

- mon-aide-cyber-api/src/serveur.ts
**Contexte**
Navigation sur le site
- Se rendre sur MAC
- Cliquer sur un lien / bouton (comme `Se connecter`
Je suis redirigé vers la page d’accueil
**Résulta attendu**
Je peux me rendre sur la page de connexion
> [CORRECTION] Corrige la redirection vers / quand la route n’est pas trouvée

- mon-aide-cyber-api/src/api/demandes/routesAPIDemandeEtreAide.ts
- mon-aide-cyber-api/src/gestion-demandes/aide/CapteurSagaDemandeAide.ts
Lorsqu’une erreur lors d’une demande d’Aide nous parvient sur MT 
Les causes racines de l’erreur ne sont pas visibles dans Sentry, nous n’avons pas de détails ou d’éléments qui nous permette d’investiguer l’erreur :
Ajouter la cause nous retourne ces détails dans Sentry (cet exemple est issu d’un environnement de dev avec une exception levée volontairement)
> [DEMANDE AIDE] Améliore la remontée des exceptions lors de la demande d’Aide afin d’avoir la cause racine

- mon-aide-cyber-api/src/infrastructure/adaptateurs/AdaptateurEnvoiMailBrevo.ts
- mon-aide-cyber-api/src/infrastructure/adaptateurs/adaptateurPThrottle.ts
- mon-aide-cyber-api/src/infrastructure/adaptateurs/adaptateursRequeteBrevo.ts
**Attention :**
Le fait de rajouter un cadencement risque de rajouter encore plus de frustration dans la communauté car il pourrait y avoir un décalage de plusieurs secondes entre le premier mail et le dernier. 
On a dû récupérer le code de [p-throttle](https://github.com/sindresorhus/p-throttle) car impossible de l’utiliser au runtime du fait de la configuration CommonJS de MAC quand `p-throttle` est un module `ES`
> [MISE EN RELATION] Cadence l’envoi de mail aux Aidants lors de la mise en relation

- mon-aide-cyber-api/src/adaptateurs/AdaptateurDeVerificationDeCGU.ts
- mon-aide-cyber-api/src/adaptateurs/AdaptateurDeVerificationDeCGUMAC.ts
- mon-aide-cyber-api/src/api/aidant/routesAPIAidantPreferences.ts
- mon-aide-cyber-api/src/api/aidant/routesAPIProfil.ts
- mon-aide-cyber-api/src/api/routesAPIDiagnostic.ts
- mon-aide-cyber-api/src/api/tableau-de-bord/routesAPITableauDeBord.ts
- mon-aide-cyber-api/test/adaptateurs/AdaptateurDeVerificationDeCGUDeTest.ts
- mon-aide-cyber-api/test/adaptateurs/AdaptateurDeVerificationDeCGUMAC.spec.ts
**L’alerte remontée lors de la vérification des CGU est obscure et ne facilite pas son identification :**
**L’origine n’est pas plus simple à trouver dans Sentry car noyée dans la page d’erreur**
L’idée est de préfixer l’erreur remontée avec le contexte dans lequel la requête a été faite, e.g `[Accède au profil] L'utilisateur voulant accéder à cette ressource n'est pas connu.`
> [REMANIEMENT] Ajoute du contexte lors de la vérification des CGU pour faciliter la compréhension des erreurs remontées

- mon-aide-cyber-api/src/adaptateurs/AdaptateurEnvoiMail.ts
- mon-aide-cyber-api/src/gestion-demandes/aide/MiseEnRelationParCriteres.ts
- mon-aide-cyber-api/src/infrastructure/adaptateurs/AdaptateurEnvoiMailBrevo.ts
- mon-aide-cyber-api/src/infrastructure/adaptateurs/AdaptateurEnvoiMailMemoire.ts
- mon-aide-cyber-api/src/infrastructure/adaptateurs/adaptateursRequeteBrevo.ts
- mon-aide-cyber-api/src/infrastructure/adaptateurs/enCadence.ts
- mon-aide-cyber-api/test/gestion-demandes/aide/MiseEnRelationParCriteres.spec.ts
- mon-aide-cyber-api/test/infrastructure/adaptateurs/enCadence.spec.ts
On reflète dans l’API de l’adaptateur l’envoi en masse, c’est un détail d’implémentation, chaque implémentation pouvant choisir de cadencer ou non
> [CORRECTION][MISE EN RELATION] Cadence correctement les appels à Brevo

- mon-aide-cyber-api/src/infrastructure/adaptateurs/AdaptateurEnvoiMailBrevo.ts
**Contexte**
Mise en relation entité Aidée - Aidants
- **Pré-requis**
- Avoir un Aidant avec des préférences à jour (Type d’entité, Secteurs d’activité, Secteurs géographique)
- Effectuer une demande d’Aide avec une entité répondant aux critères de l’Aidant
Aucun Aidant n’est contacté pour la mise en relation, les mails ne partent pas
Les Aidants répondants aux critères reçoivent un mail de mise en relation
> [MISE EN RELATION] Corrige le cadencement qui ne faisait pas partir les mails aux Aidants

- mon-aide-cyber-api/src/espace-aidant/Aidant.ts
- mon-aide-cyber-api/src/gestion-demandes/aide/MiseEnRelationParCriteres.ts
- mon-aide-cyber-api/src/infrastructure/entrepots/memoire/EntrepotMemoire.ts
- mon-aide-cyber-api/src/infrastructure/entrepots/memoire/EntrepotsMemoire.ts
- mon-aide-cyber-api/src/infrastructure/entrepots/postgres/EntrepotAidantPostgres.ts
- mon-aide-cyber-api/test/gestion-demandes/aide/MiseEnRelationParCriteres.spec.ts
- mon-aide-cyber-api/test/infrastructure/adaptateurs/enCadence.spec.ts
- mon-aide-cyber-api/test/infrastructure/entrepots/postgres/EntrepotAideConcret.spec.ts
- mon-aide-cyber-api/test/infrastructure/entrepots/postgres/EntrepotsPostgres.spec.ts
- mon-aide-cyber-api/test/infrastructure/entrepots/postgres/aideAuxTests/DictionnaireDeChiffrementAide.ts
- mon-aide-cyber-api/test/infrastructure/entrepots/postgres/aideAuxTests/EntrepotAideBrevoMemoire.ts
Afin de permettre à tous les Aidants de pouvoir participer et s’assurer que les entités Aidées peuvent obtenir un diagnostic dans un temps raisonnable, nous limitons le nombre de diagnostics par Aidant à 2 sur 30 jours glissant
> [MISE EN RELATION] Limite les Aidants pouvant postuler à 2 demandes sur 30 jours glissant

- mon-aide-cyber-api/.env.template
- mon-aide-cyber-api/src/adaptateurs/adaptateurEnvironnement.ts
- mon-aide-cyber-api/src/adaptateurs/adaptateurMessagerie.ts
- mon-aide-cyber-api/src/infrastructure/adaptateurs/AdaptateurMessagerieMattermost.ts
- mon-aide-cyber-api/test/adaptateurs/adaptateursEnvironnementDeTest.ts
De WEBHOOK_MATTERMOST_DEMANDE_DEVENIR_AIDANT_NON_TROUVEE à WEBHOOK_MATTERMOST_ACTIVATION_COMPTE_AIDANT
> [REMANIEMENT][ACTIVATION AIDANT] Renomme la variable d'environnement du webhook d'activation compte Aidant

- mon-aide-cyber-api/src/administration/aidants/par-domaine/commande.ts
Afin de pouvoir distinguer les Aidants sans SIRET
Il suffit par la suite de récupérer la sortie de la commande dans un fichier et exécuter la commande suivante :
`cat MON_FICHIER.json | jq '[.[] | select(.entite == null) | {idHashe}]` 
Cela produira la sortie suivante :
```json
[
{
"idHashe": "UN_ID"
}
]
```
> [AIDANT][GENDARMERIE] Ajoute l'entité dans la commande d'administration de recherche par domaine

- mon-aide-cyber-api/package.json
- mon-aide-cyber-api/src/administration/gendarmes/rattrapage/commande.ts
- mon-aide-cyber-api/src/administration/gendarmes/rattrapage/metAJourLesGendarmesSansEntite.ts
- mon-aide-cyber-api/src/administration/gendarmes/rattrapage/trouveLesAidantsGendarmes.ts
- mon-aide-cyber-api/test/administration/gendarmes/rattrapage/metAJourLesGendarmesSansEntite.spec.ts
- mon-aide-cyber-api/test/administration/gendarmes/rattrapage/trouveLesAidantsGendarmes.spec.ts
A l'heure actuelle, seules actions réalisées :
- liste uniquement les identifiants à modifier sans faire de persistance
> [AIDANT][GENDARMERIE] Créé la commande d'administration pour le rattrapage des gendarmes non identifiés

- mon-aide-cyber-ui/src/domaine/espace-aidant/ecran-ressources/composants/EncartContenu.tsx
Active par défaut le sous-titrage des vidéos de la page /mon-espace/ressources
> [MON ESPACE][PAGE RESSOURCES] Utilise les sous-titres par défaut lors du lancement des vidéos

- mon-aide-cyber-api/.env.template
- mon-aide-cyber-api/src/adaptateurs/adaptateurEnvironnement.ts
- mon-aide-cyber-api/src/api/webhooks/routesAPIWebhooks.livestorm.ts
- mon-aide-cyber-api/test/api/webhooks/constructeursDeWebhooks.ts
- mon-aide-cyber-api/test/api/webhooks/routesAPIWebhooks.livestorm.spec.ts
On a découvert que MAC se faisait appeler par l'intégralité des événements présents dans notre organisation sur Livestorm. Afin que l'on ne traite que les appels qui nous concernent (les sessions données par l'événement Atelier devenir Aidant)
Maintenant, on vérifie que l'id de l'événement qui nous appelle correspond à la valeur que l'on possède.
> [CORRECTION][WEBHOOK LIVESTORM] Autorise uniquement un événement Livestorm voulu à exécuter l'activation d'un compte Aidant

- mon-aide-cyber-ui/.eslintrc.cjs
- mon-aide-cyber-ui/index.html
- mon-aide-cyber-ui/package.json
- mon-aide-cyber-ui/src/lab-anssi-ui-kit.jsx.d.ts
- mon-aide-cyber-ui/src/main.tsx
- package-lock.json
Suite à la suppression du fichier de déclaration de type de l’UI-Kit, nous devons embarquer notre propre définition sans quoi le JSX ne peut être transpilé. 
Ainsi cette PR embarque le fichier de déclaration de type correspondant à la version `1.15.2` de l’UI-Kit qui était celle que nous utilisions. Il n’est pas nécessaire de déclarer tous les nouveaux types de la `1.16.0` à la `1.28.0` car nous n’utilisons aucun des nouveaux composants
> [CORRECTION] Mets à jour la librairie Lab-ANSSI-Ui-Kit afin de disposer de la nouvelle description de l'ANSSI
