betagouv/mon-aide-cyber

- .dockerignore
- Dockerfile-api
- Dockerfile-ui
- docker-compose.yml
- mon-aide-cyber-api/.eslintrc.yml
- mon-aide-cyber-api/index.js
- mon-aide-cyber-api/package.json
- mon-aide-cyber-api/src/serveur.js
- mon-aide-cyber-ui/.gitignore
- mon-aide-cyber-ui/index.html
- mon-aide-cyber-ui/package.json
- mon-aide-cyber-ui/vite.config.ts
- package-lock.json
Crée un Dockerfile pour l'environnement de dev afin de s'assurer du bon comportement lors de la phase de développement vers l'environnement cible.
- un Dockerfile pour l'interface utilisateur
- un Dockerfile pour l'API
> Initialise un Dockerfile

- .github/workflows/nodejs.yaml
- .pre-commit-config.yaml
- mon-aide-cyber-api/package.json
- afin de vérifier le formatage du code et des fichiers
- afin de lancer les tests
> Initialise la CI

- README.md
Donne le modus operandi pour:
- démarrer l'environnement d'exécution avec Docker
- Exécuter la suite de test
> [DOCUMENTATION] Ajoute le manuel d'installation du projet

- mon-aide-cyber-api/src/api/representateurs/representateurDiagnostique.ts
- mon-aide-cyber-api/src/diagnostique/donneesReferentiel.js
- mon-aide-cyber-api/src/infrastructure/adaptateurs/adaptateurTranscripteur.ts
- mon-aide-cyber-api/test/api/representateurs/representateurDiagnostique.spec.ts
- mon-aide-cyber-api/test/constructeurs/constructeurReferentiel.ts
- mon-aide-cyber-ui/src/composants/ComposantDiagnostique.tsx
- mon-aide-cyber-ui/src/domaine/diagnostique/Referentiel.ts
- mon-aide-cyber-ui/src/stories/Diagnostique.stories.tsx
- mon-aide-cyber-ui/test/consructeurs/construceurReferentiel.ts
- l'UI s'adapte aux informations transmises par l'API pour afficher l'UI correctement
- l'API transmet l'information à l'UI sur le type d'affichage désiré
> [DIAGNOSTIQUE][SAISIE-CONTEXTE] Affiche le secteur d'activité

- mon-aide-cyber-ui/src/assets/styles/_questionnaire.scss
- mon-aide-cyber-ui/src/assets/styles/index.scss
- mon-aide-cyber-ui/src/composants/ComposantDiagnostique.tsx
- mon-aide-cyber-ui/src/domaine/diagnostique/Referentiel.ts
- mon-aide-cyber-ui/src/stories/Diagnostique.stories.tsx
- mon-aide-cyber-ui/test/consructeurs/Constructeur.ts
- mon-aide-cyber-ui/test/consructeurs/construceurReferentiel.ts
- mon-aide-cyber-ui/test/consructeurs/constructeurQuestions.ts
- mon-aide-cyber-ui/test/consructeurs/constructeurReponsePossible.ts
- mon-aide-cyber-ui/test/domaine/diagnostique/reducteurs.spec.ts
Certaines réponses entrainent une question supplémentaire à choix multiple:
Le composant est capable d'afficher la question correspondante avec les différentes réponses possibles
> [DIAGNOSTIQUE][SAISIE-CONTEXTE] Permet d'afficher une question issue d'une réponse

- mon-aide-cyber-api/src/diagnostique/donneesReferentiel.ts
- mon-aide-cyber-api/src/diagnostique/referentiel.ts
- mon-aide-cyber-api/src/diagnostique/serviceDiagnostique.ts
- mon-aide-cyber-api/src/infrastructure/adaptateurs/AdaptateurDonneesMAC.ts
- mon-aide-cyber-api/test/api/testRouteDiagnostique.spec.ts
- mon-aide-cyber-api/test/constructeurs/constructeurReferentiel.ts
- mon-aide-cyber-api/test/diagnostique/serviceDiagnostique.spec.ts
- Le référentiel de données accepte que des réponses puissent avoir une question à tiroir
> [DIAGNOSTIQUE][SAISIE-CONTEXTE] Ajoute les données de l'usage du cloud

- mon-aide-cyber-api/src/adaptateurs/AdaptateurTranscripteur.ts
- mon-aide-cyber-api/src/api/representateurs/representateurDiagnostic.ts
- mon-aide-cyber-api/src/api/representateurs/types.ts
- mon-aide-cyber-api/src/diagnostic/Referentiel.ts
- mon-aide-cyber-api/src/diagnostic/donneesReferentiel.ts
- mon-aide-cyber-api/src/infrastructure/adaptateurs/adaptateurTranscripteur.ts
- mon-aide-cyber-api/test/adaptateurs/adaptateurTranscripteur.ts
- mon-aide-cyber-api/test/api/representateurs/representateurDiagnostic.spec.ts
- mon-aide-cyber-api/test/api/representateurs/transcripteursDeTest.ts
- mon-aide-cyber-api/test/constructeurs/constructeurReferentiel.ts
- mon-aide-cyber-api/test/diagnostic/ServiceDiagnostic.spec.ts
Afin d'afficher correctement la question sur l'usage du cloud
> [DIAGNOSTIQUE][SAISIE-CONTEXTE] Transcris les questions à tiroir

- mon-aide-cyber-ui/src/assets/styles/_diagnostic.scss
- mon-aide-cyber-ui/src/composants/diagnostic/ComposantDiagnostic.tsx
- mon-aide-cyber-ui/src/domaine/diagnostic/Referentiel.ts
- mon-aide-cyber-ui/src/domaine/diagnostic/reducteurDiagnostic.ts
- mon-aide-cyber-ui/src/stories/ReponsesDonneesAuDiagnostic.stories.tsx
- mon-aide-cyber-ui/test/consructeurs/constructeurReferentiel.ts
- mon-aide-cyber-ui/test/domaine/diagnostic/reducteurDiagnostic.spec.ts
- mon-aide-cyber-ui/test/infrastructure/entrepots/EntrepotsMemoire.ts
Ainsi qu'un menu vertical cliquable pour afficher les différentes thématiques
> [DIAGNOSTIC] Affiche la gouvernance

- mon-aide-cyber-ui/src/composants/diagnostic/ComposantDiagnostic.tsx
- mon-aide-cyber-ui/src/domaine/diagnostic/Diagnostic.ts
- mon-aide-cyber-ui/src/domaine/diagnostic/Referentiel.ts
- mon-aide-cyber-ui/src/domaine/diagnostic/reducteurReponse.ts
- mon-aide-cyber-ui/src/fournisseurs/FournisseurEntrepot.ts
- mon-aide-cyber-ui/src/infrastructure/entrepots/APIEntrepotDiagnostic.ts
- mon-aide-cyber-ui/src/infrastructure/entrepots/EntrepotsAPI.ts
- mon-aide-cyber-ui/src/main.tsx
- mon-aide-cyber-ui/src/stories/ReponsesDonneesAuDiagnostic.stories.tsx
- mon-aide-cyber-ui/test/constructeurs/constructeurQuestions.ts
- mon-aide-cyber-ui/test/constructeurs/constructeurReferentiel.ts
- mon-aide-cyber-ui/test/domaine/diagnostic/reducteurReponse.spec.ts
> [DIAGNOSTIC] Persiste les réponses des questions à choix multiples des questions tiroir depuis l'UI

- mon-aide-cyber-api/src/api/representateurs/representateurDiagnostic.ts
- mon-aide-cyber-api/src/api/representateurs/types.ts
- mon-aide-cyber-api/src/diagnostic/donneesReferentiel.ts
- mon-aide-cyber-api/src/infrastructure/adaptateurs/adaptateurTranscripteur.ts
- mon-aide-cyber-api/test/api/representateurs/representateurDiagnostic.spec.ts
- Prends en compte la notion de 'questions' pour les questions à dans les réponses
- Corrige la question sur les cyber attaques
> [REMANIEMENT] Modifie la représentation du diagnostic

- mon-aide-cyber-api/src/diagnostic/Diagnostic.ts
- mon-aide-cyber-api/src/diagnostic/ServiceDiagnostic.ts
- mon-aide-cyber-api/src/diagnostic/StrategieDeReponse.ts
- mon-aide-cyber-api/test/api/representateurs/representateurDiagnostic.spec.ts
- mon-aide-cyber-api/test/constructeurs/constructeurDiagnostic.ts
- mon-aide-cyber-api/test/diagnostic/Diagnostic.spec.ts
- les réponses multiples pour les QCM n'étaient prises en compte que dans le cas des questions à tiroir
> [CORRECTION] Corrige l'API pour prendre en compte les réponses aux QCM

- mon-aide-cyber-api/src/diagnostic/donneesReferentiel.ts
> [CORRECTION] Corrige les retours d'erreurs grammaticales et de typographie

- mon-aide-cyber-api/src/diagnostic/Diagnostic.ts
- mon-aide-cyber-api/test/constructeurs/constructeurReferentiel.ts
- mon-aide-cyber-api/test/diagnostic/Diagnostic.spec.ts
- mon-aide-cyber-api/test/diagnostic/ServiceDiagnostic.spec.ts
- afin de remplacer au fur et à mesure l'ancien moteur
> [DIAGNOSTIC][RECOMMANDATIONS] Fusionne les moteurs de recommandations

- mon-aide-cyber-api/index.ts
- mon-aide-cyber-api/src/api/routesAPIDiagnostic.ts
- mon-aide-cyber-api/src/domaine/BusEvenement.ts
- mon-aide-cyber-api/src/infrastructure/bus/BusEvenementMAC.ts
- mon-aide-cyber-api/src/serveur.ts
- mon-aide-cyber-api/test/api/testeurIntegration.ts
- mon-aide-cyber-api/test/infrastructure/bus/BusEvenementMAC.spec.ts
à savoir:
- Diagnostic lancé
- Réponse donnée
- Diagnostic terminé
> [REMANIEMENT] Publie les événements du diagnostic sur  le bus d'événement

- mon-aide-cyber-ui/package.json
- package-lock.json
https://github.com/betagouv/mon-aide-cyber/security/dependabot/10
> [CORRECTION] Corrige la vulnérabilité Babel levée par dependabot

- mon-aide-cyber-api/src/diagnostic/recommandations/recommandationsSecuritePoste.ts
- 'Chiffrer les disques durs des matériels nomades => 26'
> [CORRECTION] Modifie les priorisations de certaines recommandations:

- .github/workflows/storybook-tests.yml
- README.md
- mon-aide-cyber-ui/.env-template
- mon-aide-cyber-ui/src/Accueil.tsx
- mon-aide-cyber-ui/src/composants/ComposantDiagnostics.tsx
- mon-aide-cyber-ui/src/infrastructure/activation_fonctionnalites.ts
- la variable d'environnement est utilisée pour valoriser l'activation
> [DIAGNOSTIC] Empêche le lancement du diagnostic en ajoutant une variable d'environnement

- mon-aide-cyber-api/src/diagnostic/recommandations/recommandationsSecuritePoste.ts
- mon-aide-cyber-api/src/diagnostic/referentiel/donneesContexte.ts
- mon-aide-cyber-api/src/diagnostic/referentiel/donneesGouvernance.ts
- mon-aide-cyber-api/src/diagnostic/referentiel/donneesReaction.ts
- mon-aide-cyber-api/src/diagnostic/referentiel/donneesSecuriteInfrastructure.ts
- mon-aide-cyber-api/src/diagnostic/referentiel/donneesSecuritePoste.ts
- Ajout de Collectivités d'Outre-Mer
- Gouvernance, Sécurité des infrastructures, Sécurité des postes, Réaction
> [DIAGNOSTIC] Modifie certaines questions et réponses

- mon-aide-cyber-api/src/diagnostic/referentiel/donneesContexte.ts
Demander la région n'a pas d'intérêt si on demande ensuite le département : la région peut être déduite du département
Se tenir à la définition des différents type d'entreprises définies par l'Europe: https://eur-lex.europa.eu/legal-content/FR/ALL/?uri=LEGISSUM%3An26026
+ qq modifications mineures
> [DIAGNOSTIC][CONTEXTE] Modifie les libellés sur le nombre de personnes et de postes

- mon-aide-cyber-api/src/diagnostic/referentiel/donneesSecuriteAcces.ts
reformule les questions:
- acces-liste-compte-utilisateurs
- acces-utilisation-comptes-administrateurs-droits-limitee
- acces-droits-acces-utilisateurs-limites
- acces-mesures-securite-robustesse-mdp
reformule les réponses:
- acces-utilisation-comptes-administrateurs-droits-quelques-restrictions
- acces-utilisation-comptes-administrateurs-droits-justifies
corrige une faute d’orthographe dans la réponse acces-utilisation-comptes-administrateurs-droits-limitee-non
>  [DIAGNOSTIC][QUESTIONS] modifie la thématique Sécurité des accès

- mon-aide-cyber-api/src/diagnostic/referentiel/donneesGouvernance.ts
[DIAGNOSTIC][QUESTIONS][GOUVERNANCE] modifie la question gouvernanc-schema-si-industriel-a-jour et ses réponses
remplace "SI industriels" par "systèmes industriels" (appellation utilisée par l'ANSSI dans ses précédentes publications)
> [DIAGNOSTIC][QUESTIONS] modifie la thématique GOUVERNANCE

- mon-aide-cyber-api/src/adaptateurs/AdaptateurDeVerificationDeSession.ts
- mon-aide-cyber-api/src/domaine/Aggregat.ts
- AggregatNonTrouve et ErreurAccesRefuse implémentaient Error, maintenant elles l'étendent
> [REMANIEMENT] Corrige les implémentations des erreurs

- mon-aide-cyber-api/test/api/executeurRequete.ts
afin de supprimer le code mort
> [REMANIEMENT] Nettoie l'exécuteur de Requête

- mon-aide-cyber-api/src/diagnostic/referentiel/donneesSecuriteAcces.ts
[DIAGNOSTIC][QUESTIONS][SECURITEACCES] modifie la question acces-si-industriel-teletravail-acces-distants-mesures-particulieres
harmonise l'utilisation de "systèmes industriels" au lieu de "SI industriel"
>  [DIAGNOSTIC][SECURITEACCES] modifie la question sir les accès distants des systèmes industriels

- mon-aide-cyber-api/src/diagnostic/recommandations/recommandationsGouvernance.ts
- mon-aide-cyber-api/src/diagnostic/recommandations/recommandationsSecuriteAcces.ts
- mon-aide-cyber-api/src/diagnostic/recommandations/recommandationsSecuriteInfrastructure.ts
- mon-aide-cyber-api/src/diagnostic/recommandations/recommandationsSecuritePoste.ts
- mon-aide-cyber-api/src/diagnostic/referentiel/donneesContexte.ts
- mon-aide-cyber-api/src/diagnostic/referentiel/donneesGouvernance.ts
- mon-aide-cyber-api/src/diagnostic/referentiel/donneesSecuriteAcces.ts
- mon-aide-cyber-api/src/diagnostic/referentiel/donneesSecuriteInfrastructure.ts
- mon-aide-cyber-api/src/diagnostic/referentiel/donneesSecuritePoste.ts
Les thématiques `Contexte`, `Gouvernance`, `Sécurité des accès` et `Sécurité des accès` sont mises à jour:
- Contexte
- Ordonne l'affichage des régions
- Modifie les identifiants du nombre de collaborateurs
- Modifie les identifiants du nombre de poste
- Ajoute l'usurpation d'identité dans la question sur les cyber attaques
- Gouvernance
- Ajoute une question sur la RGPD (avec une nouvelle recommandation à retravailler)
- Sécurité des accès
- Suppression de la question sur les entités disposant de plusieurs sites géographiques
- Modifie les questions sur l'AD, les administrations de poste et les administrations de serveur
- Sécurité des infrastructures
- Supprime une recommandations sur les mises à jour fonctionnelles
> [RÉFÉRENTIEL] Mise à jour de thématiques

- mon-aide-cyber-ui/src/composants/Footer.tsx
Et réordonne la disposition des logos
> [REMANIEMENT] Reformule le texte du pied de page

- mon-aide-cyber-api/src/infrastructure/pdf/modeles/recommandations/gouvernance/gouvernance-infos-et-processus-a-proteger-niveau1-comment.pug
Corrige des fautes d'orthographe dans gouvernance-infos-et-processus-a-proteger-niveau1-comment.pug
> [RECOMMANDATIONS] correction de faute d’orthographe

- mon-aide-cyber-api/src/infrastructure/pdf/modeles/recommandations/gouvernance/gouvernance-schema-si-a-jour-niveau1-comment.pug
+ remplacer "SI industriel" par "systèmes industriels"
> [RECOMMANDATIONS] correction mineure (faute d’orthographe)

- mon-aide-cyber-api/src/diagnostic/referentiel/donneesReaction.ts
- mon-aide-cyber-api/src/infrastructure/entrepots/postgres/migrations/20240129134755_corrige-mesure-sauvegarde.ts
**Contexte**
La génération de la restitution affiche une mesure sur les sauvegardes alors que la réponse au diagnostic met en avant que des sauvegardes sont faites.
- Lancer un diagnostic
- Se rendre sur la thématique `Réaction`
- Répondre à la question `Des sauvegardes régulières des données et des systèmes d'information sont-elles réalisées ?` par  `Des sauvegardes des données et des systèmes sont réalisées de manière automatique et régulière`
- Répondre par l'affirmative aux 2 sous questions
- Cliquer sur `Quitter le diagnostic`
La restitution remonte la mesure 
```
6 . En complément des sauvegardes régulièrement réalisées et stockées sur le réseau, disposer 
d'une sauvegarde des données critiques stockées dans un environnement sécurisé, isolé 
de …
```
> [CORRECTION] Corrige la réponse Oui à la question sur les sauvegardes automatiques et régulières

- mon-aide-cyber-api/src/infrastructure/restitution/mesures/postes/securite-poste-maj-fonctionnelles-et-securite-deployees-niveau1-comment.pug
> [DIAGNOSTIC][MESURES] Mets à jour la mesure sur comment sécuriser les postes en appliquant les mises à jour fonctionnelles

- mon-aide-cyber-ui/src/assets/styles/_footer.desktop.scss
- mon-aide-cyber-ui/src/composants/Footer.tsx
> [FOOTER] harmonise la taille des icones

- mon-aide-cyber-ui/src/assets/styles/_accueil.scss
- mon-aide-cyber-ui/src/assets/styles/index.desktop.scss
- mon-aide-cyber-ui/src/assets/styles/index.mobile.scss
Bug observé : ![bug](https://github.com/betagouv/mon-aide-cyber/assets/3235855/a0e977b4-030f-4f01-9c46-6ba795378658)
Correction : ![2024-03-11_16-38](https://github.com/betagouv/mon-aide-cyber/assets/3235855/ac8d1b6f-359e-4322-b78d-f1ad7356ec99)
> [CORRIGE][ACCUEIL] affiche les tuiles correctement quand la taille de la fenetre est moyenne

- mon-aide-cyber-api/src/diagnostic/referentiel/donneesSecuriteInfrastructure.ts
- mon-aide-cyber-api/src/infrastructure/restitution/mesures/reaction/reaction-dispositif-gestion-crise-adapte-defini-niveau1-comment.pug
- lie la mesure de niveau 2 à la question `securite-infrastructure-pare-feu-deploye`
- corrige le formattage de la section comment de la mesure de niveau 1 `reaction-dispositif-gestion-crise-adapte-defini`
> [CORRECTION] référentiel

- mon-aide-cyber-api/src/infrastructure/restitution/mesures/infras/securite-infrastructure-pare-feu-deploye-interconnexions-protegees-niveau2-comment.pug
> [CORRECTION] coquille dans les mesures de niveau 2 des interconnexions protégées

- mon-aide-cyber-api/src/espace-aidant/tableau-de-bord/ServiceTableauDeBord.ts
- mon-aide-cyber-api/test/espace-aidant/tableau-de-bord/ServiceTableauDeBord.spec.ts
- mon-aide-cyber-api/test/espace-aidant/tableau-de-bord/routesAPITableauDeBord.spec.ts
- mon-aide-cyber-ui/src/composants/espace-aidant/tableau-de-bord/ComposantDiagnostics.tsx
- mon-aide-cyber-ui/src/composants/espace-aidant/tableau-de-bord/TableauDeBord.tsx
- mon-aide-cyber-ui/src/composants/utilisateur/ComposantMenuUtilisateur.tsx
- Le titre devient ’Mes diagnostics’
- L’entrée ’Diagnostics’ du  menu utilisateur devient ’Mes diagnostics’
- la colonne ’Département’ devient ’Secteur géographique’
> [REMANIMENT] Applique quelques renommages sur la page des diagnostics

- mon-aide-cyber-ui/src/assets/styles/_input.scss
- mon-aide-cyber-ui/src/composants/auto-completion/AutoCompletion.tsx
- mon-aide-cyber-ui/src/composants/auto-completion/reducteurAutoCompletion.ts
- mon-aide-cyber-ui/src/composants/demande-aide/SaisieInformations.tsx
- mon-aide-cyber-ui/src/composants/demande-aide/reducteurSaisieInformations.tsx
- mon-aide-cyber-ui/src/stories/AutoCompletion.stories.tsx
- mon-aide-cyber-ui/test/composants/auto-completion/reducteurAutoCompletion.spec.ts
- mon-aide-cyber-ui/test/composants/demande-aide/reducteurSaisieInformations.spec.tsx
Afin de :
- laisser la responsabilité de ce qui est saisi au composant
- distinguer la sélection d’un choix de la saisie utilisateur
> [CORRECTION] Améliore le composant d’auto complétion

- mon-aide-cyber-api/src/api/representateurs/RepresentationGroupee.ts
- mon-aide-cyber-api/src/api/representateurs/representateurDiagnostic.ts
- mon-aide-cyber-api/src/api/representateurs/types.ts
- mon-aide-cyber-api/src/diagnostic/referentiel/donneesContexte.ts
- mon-aide-cyber-api/src/infrastructure/adaptateurs/transcripteur/transcripteurContexte.ts
- mon-aide-cyber-api/test/api/representateurs/representateurDiagnostic.spec.ts
- mon-aide-cyber-api/test/api/representateurs/transcripteursDeTest.ts
- mon-aide-cyber-ui/src/composants/diagnostic/ComposantDiagnostic.tsx
- mon-aide-cyber-ui/src/domaine/diagnostic/Referentiel.ts
- mon-aide-cyber-ui/src/fournisseurs/api/APIDiagnostic.ts
- mon-aide-cyber-ui/src/stories/AfficheDiagnostic.stories.tsx
- mon-aide-cyber-ui/test/constructeurs/constructeurQuestions.ts
- mon-aide-cyber-ui/test/constructeurs/constructeurReferentiel.ts
- mon-aide-cyber-ui/test/constructeurs/constructeurReponsePossible.ts
- Permets de filtrer les départements dans le diagnostic avec le numéro de département
- Affiche le numéro du département suivi de son nom `67 - Bas-Rhin`
> [AUTOCOMPLETION] Améliore l’auto-complétion au niveau de la liste des départements dans le diagnostic

- mon-aide-cyber-api/src/infrastructure/adaptateurs/transcripteur/transcripteurSecuriteInfrastructure.ts
- mon-aide-cyber-api/src/infrastructure/restitution/mesures/postes/securite-poste-maj-fonctionnelles-et-securite-deployees-niveau1-comment.pug
- mon-aide-cyber-ui/src/assets/styles/_diagnostic.scss
- mon-aide-cyber-ui/src/composants/diagnostic/ConteneurReponsePossible.tsx
> [CORRECTION][REFERENTIEL] Corrige plusieurs éléments mineurs d'affichage et de typos

- mon-aide-cyber-api/src/diagnostic/mesures/mesuresSecuriteAcces.ts
- mon-aide-cyber-api/src/diagnostic/mesures/mesuresSecuriteInfrastructure.ts
- mon-aide-cyber-api/src/diagnostic/mesures/mesuresSecuritePoste.ts
- mon-aide-cyber-api/src/diagnostic/referentiel/donneesSecuriteAcces.ts
- mon-aide-cyber-api/src/diagnostic/referentiel/donneesSecuritePoste.ts
- mon-aide-cyber-api/src/infrastructure/adaptateurs/transcripteur/info-bulles/acces/utilisateurs-administrateurs.pug
- mon-aide-cyber-api/src/infrastructure/adaptateurs/transcripteur/info-bulles/contexte/nombre-de-postes.pug
- mon-aide-cyber-api/src/infrastructure/adaptateurs/transcripteur/info-bulles/gouvernance/cnil.pug
- mon-aide-cyber-api/src/infrastructure/adaptateurs/transcripteur/info-bulles/postes/edr-installe.pug
- mon-aide-cyber-api/src/infrastructure/adaptateurs/transcripteur/info-bulles/reaction/suivi-alertes-vulnerabilites.pug
- mon-aide-cyber-api/src/infrastructure/adaptateurs/transcripteur/info-bulles/reaction/veille-vulnerabilites-entites-publiques.pug
- mon-aide-cyber-api/src/infrastructure/adaptateurs/transcripteur/transcripteurGouvernance.ts
- mon-aide-cyber-api/src/infrastructure/restitution/mesures/gouvernance/gouvernance-exigence-cyber-securite-presta-niveau1-comment.pug
- mon-aide-cyber-api/src/infrastructure/restitution/mesures/gouvernance/gouvernance-exigence-cyber-securite-presta-si-industriel-niveau1-comment.pug
- mon-aide-cyber-api/src/infrastructure/restitution/mesures/infras/securite-infrastructure-mises-a-jour-fonctionnelles-securite-equipements-securite-deployees-niveau1-comment.pug
- mon-aide-cyber-api/src/infrastructure/restitution/mesures/infras/securite-infrastructure-mises-a-jour-fonctionnelles-securite-equipements-securite-deployees-niveau1-pourquoi.pug
- mon-aide-cyber-api/src/infrastructure/restitution/mesures/infras/securite-infrastructure-mises-a-jour-fonctionnelles-securite-equipements-securite-deployees-niveau2-comment.pug
- mon-aide-cyber-api/src/infrastructure/restitution/mesures/infras/securite-infrastructure-mises-a-jour-fonctionnelles-securite-equipements-securite-deployees-niveau2-pourquoi.pug
- mon-aide-cyber-api/src/infrastructure/restitution/mesures/infras/securite-infrastructure-mises-a-jour-fonctionnelles-securite-systemes-exploitation-securite-deployees-niveau1-comment.pug
- mon-aide-cyber-api/src/infrastructure/restitution/mesures/infras/securite-infrastructure-mises-a-jour-fonctionnelles-securite-systemes-exploitation-securite-deployees-niveau1-pourquoi.pug
- mon-aide-cyber-api/src/infrastructure/restitution/mesures/infras/securite-infrastructure-mises-a-jour-fonctionnelles-securite-systemes-exploitation-securite-deployees-niveau2-comment.pug
- mon-aide-cyber-api/src/infrastructure/restitution/mesures/infras/securite-infrastructure-mises-a-jour-fonctionnelles-securite-systemes-exploitation-securite-deployees-niveau2-pourquoi.pug
Pour : 
- Mesures :
- Gouvernance
- Sécurité des accès
- Sécurité des infrastructures
- Sécurité des postes
- Référentiel :
- Sécurité des accès
- Sécurité des postes
- Infobulles
> [CORRECTION] [DIAGNOSTIC] Mets à jour le référentiel, les mesures et les infobulles

- mon-aide-cyber-api/src/api/gestionnaires/erreurs.ts
- mon-aide-cyber-api/src/api/routesAPIEspaceAidant.ts
- mon-aide-cyber-api/src/api/routesAPIProfil.ts
- mon-aide-cyber-api/src/api/validateurs/validateurs.ts
- mon-aide-cyber-api/test/api/gestionnaires/erreurs.spec.ts
- sur la création de l’espace Aidant
- sur la modification du mot de passe sur le profil
> [SENTRY] Ne consigne pas les erreurs levées par la validation :

- mon-aide-cyber-api/src/api/aide/routesAPIAideDemande.ts
- mon-aide-cyber-api/src/gestion-demandes/aide/CapteurSagaDemandeAide.ts
- mon-aide-cyber-api/src/infrastructure/bus/BusCommandeMAC.ts
- mon-aide-cyber-api/test/gestion-demandes/aide/CapteurSagaDemandeAide.spec.ts
- bouge le domaine demande-aide comme sous domaine aide dans gestion-demandes
> [REFACTO] Fais apparaître le domaine gestion-demandes

- mon-aide-cyber-api/src/authentification/CapteurCommandeCreeCompteAidant.ts
- mon-aide-cyber-api/test/authentification/CapteurCommandeCreeCompteAidant.spec.ts
- Une erreur est remontée, cette erreur n’est pas interceptée par `erreur.ts` car nous ne sommes pas dans un contexte API / ExpressJS
> [DEVENIR AIDANT] Empêche la création de comptes en doublon

- mon-aide-cyber-api/src/api/statistiques/routesStatistiques.ts
- mon-aide-cyber-api/src/infrastructure/entrepots/postgres/EntrepotStatistiquesPostgres.ts
- mon-aide-cyber-api/test/api/statistiques/routesStatistiques.spec.ts
- mon-aide-cyber-api/test/infrastructure/entrepots/postgres/EntrepotStatistiquesPostgres.spec.ts
- mon-aide-cyber-api/test/utilitaires/nettoyeurBDD.ts
Intègre les 500 diagnostics issus de la version Excel et ceux faits en environnement de démo
> [CORRECTION][STATISTIQUES] Corrige la requête de recherche du nombre de diagnostics

- mon-aide-cyber-api/src/diagnostic/referentiel/donneesContexte.ts
- mon-aide-cyber-api/src/gestion-demandes/departements.ts
**Contexte**
Sélection des départements dans les listes déroulantes de 
- demande devenir Aidant
- demande être Aidé
- contexte du diagnostic 
1. Se rendre sur l’une des pages suivantes `demande devenir Aidant` ou `demande être aidé` :
- Dans liste déroulante des départements, sélectionner un département des DROM-COM parmi la liste
```
'Collectivité de Saint-Martin',
'Collectivité de Saint-Barthélémy',
'Collectivité de Saint-Pierre et Miquelon',
'Collectivité de Wallis & Futuna',
'Collectivité de Polynésie Française',
'Collectivité de Nouvelle-Calédonie',
```
2. Créer un diagnostic :
- Choisir un département des DROM-COM dans la liste des départements parmi
```
'Collectivité de Saint-Martin',
'Collectivité de Saint-Barthélémy',
'Collectivité de Saint-Pierre et Miquelon', …
```
> [CORRECTION] Corrige les codes des départements des DROM-COM

- mon-aide-cyber-api/src/api/adaptateurLimiteurTraffic.ts
- mon-aide-cyber-api/src/api/annuaire-aidants/routeAPIAnnuaireAidants.ts
- mon-aide-cyber-api/src/api/demandes/routesAPIDemandeSolliciterAide.ts
- mon-aide-cyber-api/src/api/routesAPIAuthentification.ts
- mon-aide-cyber-api/src/serveur.ts
- Par défaut : 100 appels max sur une période de 5 minutes
- Authentification : 5 appels max sur une période de 5 minutes
- Annuaire Aidants : 100 appels max sur une période de 5 minutes
- Sollicitation Aide : 20 appels max sur une période de 5 minutes
> [TECHNIQUE][RATE-LIMIT] Ajoute le rate limit sur les ressources suivantes :

- mon-aide-cyber-api/src/infrastructure/entrepots/postgres/migrations/20241107130215_met-a-jour-les-donnees-utilisateurs.ts
- Supprime les préférences
- Supprime le consentementAnnuaire
> [REMANIEMENT][AIDANTS] Mets à jour la table utilisateurs :

- mon-aide-cyber-api/src/infrastructure/entrepots/postgres/knexfile.ts
- mon-aide-cyber-api/vitest.config.ts
Afin d’augmenter le pool maximum dans les tests
> [TECHNIQUE] Crée des variables d’environnement pour le pool de la base de données

- mon-aide-cyber-api/src/api/adaptateurLimiteurTraffic.ts
- mon-aide-cyber-api/src/api/auto-diagnostic/routesAPIAutoDiagnostic.ts
- POST : 5 minutes, 10 appels
- GET : 5 minutes, 20 appels
- PATCH : 5 minutes, 100 appels
- GET Restitution : 5 minutes, 20 appels
> [DIAGNOSTIC LIBRE ACCES] Ajoute un limiteur de traffic sur les routes du diagnostic en libre accès

- .github/workflows/deploiement.yml
Cette PR rajoute un `.yml` qui permet de déployer vers Clever.
C'est le même workflow que les autres produits du Lab.
> [CI/CD] Crée le workflow de déploiement vers Clever

- mon-aide-cyber-ui/src/assets/styles/_maintenance.scss
- mon-aide-cyber-ui/src/composants/alertes/BandeauMaintenance.tsx
A merger APRÈS avoir modifié la variable d'environnement sur DEMO PROD.
Cela permettra d'avoir la modification directement au redéploiement lié à ce commit poussé
A MERGER LE 18 Décembre
> [REMANIEMENT][BANDEAU MAINTENANCE] Modifie la couleur du bandeau et permet de le masquer

- mon-aide-cyber-api/src/api/gestionnaires/erreurs.ts
- mon-aide-cyber-api/src/api/routeAPIContexte.ts
- mon-aide-cyber-api/src/api/routesAPIUtilisateur.ts
- mon-aide-cyber-api/src/espace-aidant/ServiceAidant.ts
- mon-aide-cyber-api/src/espace-aidant/ServiceAidantMAC.ts
- mon-aide-cyber-api/src/infrastructure/entrepots/postgres/EntrepotProfilAidantPostgres.ts
- mon-aide-cyber-api/test/api/routeAPIContexte.spec.ts
- mon-aide-cyber-api/test/api/routesAPIUtilisateur.spec.ts
- mon-aide-cyber-api/test/espace-aidant/ServiceAidantMAC.spec.ts
**Contexte**
Accès à l’espace Aidant via ProConnect
- Prérequis
- Disposer d’un accès ProConnect
- Avoir un compte Aidant
- Ne pas avoir de compte d’authentification MAC
- Se connecter via ProConnect
- Essayer d’accéder à son espace Aidant
L’Aidant ne peut accéder à son espace.
L’Aidant peut accéder à son espace
> [CORRECTION][PRO CONNECT] Corrige les appels pour vérifier l’utilisateur connecté via ProConnect

- mon-aide-cyber-api/package.json
- package-lock.json
- [Lien dependabot](https://github.com/betagouv/mon-aide-cyber/security/dependabot/56)
> [CORRECTION][SECURITE] Mets à jour vitest suite à une alerte de sécurité sur la dépendance vitest@1.6.0

- .github/workflows/checkov.yml
- .github/workflows/codeql.yaml
- .github/workflows/deploiement.yml
- .github/workflows/nodejs.yaml
- .github/workflows/storybook-tests.yml
Le CIS propose un [benchmark](https://www.cisecurity.org/benchmark/software-supply-chain-security) pour la configuration sécurisée de GitHub et [checkov](https://www.checkov.io/1.Welcome/What%20is%20Checkov.html) valide automatiquement ces règles ainsi que quelques autres.
Cette PR met ces contrôles en place sur le projet avec [checkov-action](https://github.com/bridgecrewio/checkov-action).
Cette PR intègre également les changements nécessaires pour se conformer à ces recommandations :
diminuer les permissions des jobs CI
ignorer les règles sur docker dans la mesure où le Dockerfile ne part pas en production, il est uniquement utilisé à des fins de test en local.
> [SECURITE] Mets en place Checkov

- clevercloud/cron.json
- mon-aide-cyber-api/src/infrastructure/taches/tacheExtractionCOT.ts
> [TEST][EXTRACTION COT] Exécute la tâche d’extraction toutes les minutes

- mon-aide-cyber-api/src/espace-admin/extraction/Extraction.ts
- mon-aide-cyber-api/src/gestion-demandes/devenir-aidant/CapteurCommandeDevenirAidant.ts
- mon-aide-cyber-api/src/gestion-demandes/devenir-aidant/DemandeDevenirAidant.ts
- mon-aide-cyber-api/src/gestion-demandes/devenir-aidant/ServiceDemandeDevenirAidant.ts
- mon-aide-cyber-api/src/infrastructure/taches/tacheExtractionCOT.ts
- mon-aide-cyber-api/test/constructeurs/constructeurDemandesDevenirAidant.ts
- mon-aide-cyber-api/test/espace-admin/extraction/Extraction.spec.ts
Les informations supplémentaires sont :
- Le nom de l’entité morale
- Le fait si la demande est en attente d’adhésion à une association
> [EXTRACTION COT] Ajoute des colonnes dans l’onglet Demandes devenir Aidant

- mon-aide-cyber-api/src/api/routesAPIAuthentification.ts
- mon-aide-cyber-api/src/api/routesAPIUtilisateur.ts
- mon-aide-cyber-api/test/api/routesAPIAuthentification.spec.ts
- mon-aide-cyber-api/test/api/routesAPIUtilisateur.spec.ts
**Contexte**
Validation profil
- Avoir un compte Aidant sans date de validation des CGU (Utilisateur jamais connecté)
- Se rendre sur la page de connexion
- Se connecter avec son compte MAC
- Il est demandé à l’utilisateur de valider les CGU
- L’état de l’Aidant en BDD est incohérent
- Il est demandé à l’utilisateur de faire un choix d’utilisation du service (Utilisateur inscrit / Aidant)
- L’état de l’Aidant en BDD est cohérent
Les parties de code incriminées sont celles-là :
- `mon-aide-cyber-api/src/api/routesAPIUtilisateur.ts`
```
if (!utilisateur.dateValidationCGU) {
if (utilisateur.profil === 'UtilisateurInscrit') {
return reponseOK(
constructeurActionsHATEOAS()
.pour({ contexte: 'valider-signature-cgu' })
.pour({
contexte: …
```
> [CORRECTION][CHOIX UTILISATION MAC] Corrige les actions renvoyées dans le cas d’un Aidant qui ne s’est jamais connecté

- mon-aide-cyber-ui/src/domaine/gestion-demandes/parcours-aidant/choix-type-aidant/ChoixTypeAidant.tsx
Lors du choix ’Pas encore adhérent d’une association mais prêt à le devenir’
> [RELAIS ASSOCIATIFS] Ajoute le lien vers la page des relais associatifs

- docker-compose.yml
- mon-aide-cyber-api/.env.template
- mon-aide-cyber-api/src/api/pro-connect/routeProConnect.ts
- mon-aide-cyber-api/src/domaine/erreurMAC.ts
- mon-aide-cyber-api/tsconfig.json
Cette PR est le fruit de mon démarrage sur MAC.
Elle corrige des petites choses qui ont empêché le projet de démarrer immédiatement.
> [DEV] Soins divers

- mon-aide-cyber-api/src/api/associations/referentiel.yaml
mise à jour suite à relecture Faustine & Martin du 4/03
> [ASSOCIATIONS NON REFERENCEES] Ajoute des associations au référentiel

- mon-aide-cyber-api/src/api/associations/referentiel.yaml
relecture du catalogue Martin 10/03
> [RELAIS ASSOCIATIFS] Ajoute de nouveaux relais

- mon-aide-cyber-api/src/api/associations/referentiel.yaml
- mon-aide-cyber-ui/src/composants/diagnostic/ComposantLancerDiagnostic.tsx
Ajoute une association. 
On en profite pour supprimer un `-` disgracieux.
> [RELAIS ASSOCIATIF] Mise à jour

- mon-aide-cyber-ui/src/assets/styles/_tableau-de-bord.scss
- mon-aide-cyber-ui/src/domaine/espace-aidant/ecran-diagnostics/EcranDiagnostics.tsx
> [WORDING] Retire l'avant-propos à propos des CGUs sur le tableau de bord

- mon-aide-cyber-api/index.ts
- mon-aide-cyber-api/src/adaptateurs/AdaptateurRepertoireDeContactsBrevo.ts
- mon-aide-cyber-api/src/adaptateurs/AdaptateurRepertoireDeContactsVide.ts
- mon-aide-cyber-api/src/api/pro-connect/routeProConnect.ts
- mon-aide-cyber-api/src/api/routesAPIUtilisateur.ts
- mon-aide-cyber-api/src/contacts/RepertoireDeContacts.ts
- mon-aide-cyber-api/src/espace-aidant/CapteurCommandeCreeEspaceAidant.ts
- mon-aide-cyber-api/src/espace-utilisateur-inscrit/CapteurCommandeCreerEspaceUtilisateurInscrit.ts
- mon-aide-cyber-api/src/espace-utilisateur-inscrit/ServiceUtilisateurInscritMAC.ts
- mon-aide-cyber-api/src/gestion-demandes/aide/CapteurCommandeCreerDemandeAide.ts
- mon-aide-cyber-api/src/gestion-demandes/aide/CapteurCommandeMettreAJourDemandeAide.ts
- mon-aide-cyber-api/src/gestion-demandes/aide/DemandeAide.ts
- mon-aide-cyber-api/src/infrastructure/adaptateurs/adaptateursRequeteBrevo.ts
- mon-aide-cyber-api/src/infrastructure/brevo/ConstructeursBrevo.ts
- mon-aide-cyber-api/src/infrastructure/bus/BusCommandeMAC.ts
- mon-aide-cyber-api/src/infrastructure/entrepots/postgres/EntrepotAideConcret.ts
- mon-aide-cyber-api/src/infrastructure/entrepots/postgres/EntrepotsMAC.ts
- mon-aide-cyber-api/src/serveur.ts
- mon-aide-cyber-api/test/adaptateurs/AdaptateurRepertoireDeContactsMemoire.ts
- mon-aide-cyber-api/test/adaptateurs/adaptateursRequeteBrevo.spec.ts
- mon-aide-cyber-api/test/api/testeurIntegration.ts
- mon-aide-cyber-api/test/espace-aidant/CapteurCommandeCreeEspaceAidant.spec.ts
- mon-aide-cyber-api/test/espace-utilisateur-inscrit/CapteurCommandeCreerEspaceUtilisateurInscrit.spec.ts
- mon-aide-cyber-api/test/espace-utilisateur-inscrit/ServiceUtilisateurInscritMAC.spec.ts
- mon-aide-cyber-api/test/infrastructure/entrepots/postgres/EntrepotAideConcret.spec.ts
Pour rappel, les types de profils sont : 
- UTILISATEUR_INSCRIT
- AIDANT
- AIDE
> [SYNCHRONISATION BREVO] Créé les contacts dans BREVO avec les profils adéquats pour tous les types de profils

- mon-aide-cyber-api/src/api/demandes/routesAPIDemandeEtreAide.ts
- mon-aide-cyber-api/src/api/gestionnaires/erreurs.ts
- mon-aide-cyber-api/src/gestion-demandes/aide/CapteurSagaDemandeAide.ts
- mon-aide-cyber-api/src/infrastructure/entrepots/memoire/EntrepotMemoire.ts
- mon-aide-cyber-api/test/api/demandes/routesAPIDemandeEtreAide.spec.ts
- mon-aide-cyber-api/test/gestion-demandes/aide/CapteurSagaDemandeAide.spec.ts
N'effectue pas de recherche de demande d'Aide si l'utilisateur en relation n'existe pas
> [CORRECTION][DEMANDE AIDE] Ne mets pas à jour de demande d'Aide si l'utilisateur en relation n'existe pas

- mon-aide-cyber-ui/package.json
- package-lock.json
https://github.com/betagouv/mon-aide-cyber/security/dependabot/60
> [SECURITE] Mets à jour la version de babel suite à une alerte de sécurité dependabot

- mon-aide-cyber-api/src/api/demandes/routesAPIDemandeEtreAide.ts
- mon-aide-cyber-api/src/gestion-demandes/departements.ts
- mon-aide-cyber-api/test/api/demandes/routesAPIDemandeEtreAide.spec.ts
On place le contrôle sur l’API plutôt que de laisser la recherche départements exploser Permet d’ouvrir l’API aux besoins de MSC : On sera en mesure de fournir un meilleur retour en cas d’erreur
> [DEMANDE AIDE] Effectue une demande d’Aide en fournissant le code du département

- mon-aide-cyber-ui/src/composants/diagnostic/ComposantLancerDiagnostic.tsx
Lien fourni dans la modale de création de diagnostic
> [MISE EN RELATION] Ouvre le lien vers la demande d’Aide dans un nouvel onglet du navigateur

- mon-aide-cyber-ui/index.html
- mon-aide-cyber-ui/package.json
- mon-aide-cyber-ui/src/composants/layout/header/NavigationPublique.tsx
- mon-aide-cyber-ui/src/composants/layout/header/navigation-publique.scss
- package-lock.json
- **Version Mobile :**
- **Version Desktop :**
> [MISE EN RELATION] Intègre le bouton Votre diagnostic cyber gratuit amenant vers MesServicesCyber

- mon-aide-cyber-ui/src/composants/atomes/Lien/BoutonDemandeAide.tsx
- mon-aide-cyber-ui/src/composants/atomes/Lien/bouton-demande-aide.scss
- mon-aide-cyber-ui/src/composants/communs/tuiles/TuileActionDemandeAide.tsx
- mon-aide-cyber-ui/src/composants/diagnostic/ComposantRestitution/HeaderRestitution.tsx
- mon-aide-cyber-ui/src/composants/diagnostic/EcranDiagnosticAidant.tsx
- mon-aide-cyber-ui/src/domaine/auto-diagnostic/EcranDemandeAutodiagnostic.tsx
- mon-aide-cyber-ui/src/domaine/vitrine/ecran-annuaire/composants/liste-aidants/ListeAidants.tsx
- mon-aide-cyber-ui/src/domaine/vitrine/ecran-beneficier-du-dispositif/composants/FocusRestitution.tsx
- mon-aide-cyber-ui/src/domaine/vitrine/ecran-beneficier-du-dispositif/composants/HeroDemandeAide.tsx
- mon-aide-cyber-ui/src/domaine/vitrine/ecran-beneficier-du-dispositif/composants/QuiEstConcerne.tsx
- mon-aide-cyber-ui/src/infrastructure/mes-services-cyber/liens.ts
Les liens modifiés :
- Auto diagnostic
- Bouton `Quitter` de l’auto diagnostic
- Bouton `Quitter` de la restitution de l’auto diagnostic
- Annuaire des Aidants
- Tuile `Bénéficier de MonAideCyber`
- Liens sur la page `Bénéficier du dispositif`
> [MISE EN RELATION] Modifie les liens de demande d’Aide pour pointer vers MesServicesCyber

- mon-aide-cyber-ui/src/composants/layout/header/NavigationPublique.tsx
- mon-aide-cyber-ui/src/infrastructure/mes-services-cyber/liens.ts
Cette PR indique l'origine du débranchement vers MSC, pour faciliter le suivi du trafic.
> Lien vers cyberdépart

- mon-aide-cyber-ui/index.html
- mon-aide-cyber-ui/package.json
- package-lock.json
CF [PR UI Kit](https://github.com/betagouv/lab-anssi-ui-kit/pull/45)
> [CORRECTION] Corrige l’affichage du résumé PSSI de la page sécurité

- mon-aide-cyber-api/src/gestion-demandes/departements.ts
- mon-aide-cyber-api/test/api/demandes/routeAPIDemandeDevenirAidant.spec.ts
- mon-aide-cyber-api/test/api/demandes/routesAPIDemandeEtreAide.spec.ts
- mon-aide-cyber-api/test/espace-aidant/CapteurCommandeCreeEspaceAidant.spec.ts
- mon-aide-cyber-api/test/gestion-demandes/devenir-aidant/CapteurCommandeDevenirAidant.spec.ts
**Contexte**
Demande d’Aide
- Effectuer une demande de diagnostic
- Saisir une entité domiciliée dans un des 9 premiers départements (ain, aisne, allier, alpesDeHauteProvence, alpesMaritimes, ardeche, ardennes, ariege, hautesAlpes)
- Remplir la demande d’Aide
- Cliquer sur `Envoyer`
- La demande d’Aide ne peut aboutir
- La demande d’Aide aboutit
> [CORRECTION][DEMANDE AIDE] Corrige pour les départements ayant un code compris entre 1 et 9

- mon-aide-cyber-api/src/api/associations/referentiel.yaml
On ajoute un détail sur le CESIN
> Ajout sur relais associatif

- mon-aide-cyber-api/src/gestion-demandes/aide/CapteurSagaDemandeAide.ts
- mon-aide-cyber-api/src/gestion-demandes/aide/MiseEnRelationDirecteAidant.ts
- mon-aide-cyber-api/src/gestion-demandes/aide/MiseEnRelationDirecteUtilisateurInscrit.ts
- mon-aide-cyber-api/src/gestion-demandes/aide/MiseEnRelationParCriteres.ts
- mon-aide-cyber-api/src/gestion-demandes/aide/miseEnRelation.ts
- mon-aide-cyber-api/src/infrastructure/entrepots/postgres/EntrepotJournalisationPostgres.ts
- mon-aide-cyber-api/test/constructeurs/constructeursAidantUtilisateurInscritUtilisateur.ts
- mon-aide-cyber-api/test/gestion-demandes/aide/CapteurSagaDemandeAide.spec.ts
- mon-aide-cyber-api/test/infrastructure/entrepots/postgres/EntrepotJournalisationPostgres.spec.ts
- Pour tous : le type d’entité, les secteurs d’activité, le département
- Par critères : le nombre d’aidants
- Directe Aidant : l’identifiant de l’aidant
- Directe utilisateur inscrit : l’identifiant de l’utilisateur inscrit
> [MISE EN RELATION][METABASE] Enrichis l’événement AIDE_CREE en ajoutant des informations propres à chaque type de mise en relation

- mon-aide-cyber-api/src/api/aidant/routesAPIAidantRepondreAUneDemande.ts
- mon-aide-cyber-api/src/api/aidant/tokenAttributionDemandeAide.ts
- mon-aide-cyber-api/src/gestion-demandes/aide/CapteurCommandeAttribueDemandeAide.ts
- mon-aide-cyber-api/test/api/aidant/routesAPIAidantRepondreAUneDemande.spec.ts
- mon-aide-cyber-ui/src/domaine/gestion-demandes/repondre-a-une-demande/EcranRepondreAUneDemande.tsx
- mon-aide-cyber-ui/src/domaine/gestion-demandes/repondre-a-une-demande/composants/ConfirmationReponseALaDemande.tsx
- mon-aide-cyber-ui/src/domaine/gestion-demandes/repondre-a-une-demande/composants/DemandeDejaPourvue.tsx
- mon-aide-cyber-ui/src/domaine/gestion-demandes/repondre-a-une-demande/composants/confirmation-reponse-a-la-demande.scss
URLs disponibles pour tester :
- **OK :** /repondre-a-une-demande?token=eyJkZW1hbmRlIjoiYWU5MDRmZDEtYjQzMC00YTFiLWE3OGMtZThiMmU2NWQyZDEyIiwiYWlkYW50IjoiMDgyZGMyYjctMzhiYS00OWZiLTgwMDMtZmVmMWY3YjE1NWZhIn0=
- **KO :** /repondre-a-une-demande?token=eyJkZW1hbmRlIjoiYmU5MDRmZDEtYjQzMC00YTFiLWE3OGMtZThiMmU2NWQyZDEyIiwiYWlkYW50IjoiYjIwMDIwNDEtZWRmZC00ODEwLThlY2UtYjM4NWUzZmQ5YWM1In0=
> [MISE EN RELATION] Affiche l’écran de demande d’Aide déjà pourvue

- .github/workflows/nodejs.yml
- .gitignore
- mon-aide-cyber-api/package.json
- mon-aide-cyber-api/vitest.config.ts
- mon-aide-cyber-ui/package.json
- mon-aide-cyber-ui/vitest.config.ts
… pour qu'on soit plus efficace à comprendre quel test échoue quand la CI est cassée.
> [CI/CD] Produis un rapport de test

- mon-aide-cyber-api/src/adaptateurs/fabriqueConsommateursEvenements.ts
- mon-aide-cyber-api/src/journalisation/evenements.ts
C'était un oubli de ne pas le faire.
> [POSTULER] Envoie vers Metabase les événements de demande d'aide pourvue

- mon-aide-cyber-ui/src/composants/layout/Header.tsx
Le nouveau menu de navigation :
> [NAVIGATION] Retravaille les éléments du menu

- mon-aide-cyber-api/src/api/demandes/routeAPIDemandeDevenirAidant.ts
- mon-aide-cyber-api/test/api/demandes/constructeurRequeteDemandeDevenirAidant.ts
- mon-aide-cyber-api/test/api/demandes/routeAPIDemandeDevenirAidant.spec.ts
Permet, une fois les étapes de la demande devenir Aidant validées d’arriver sur cette page :
Et d’être redirigé sur l’espace Aidant lorsque l’on clique sur le bouton :
> [INSCRIPTION] Conserve la validation des CGU lors de l’inscription d’un utilisateur qui fait le choix de devenir Aidant

- mon-aide-cyber-api/src/api/webhooks/routesAPIWebhooks.ts
- mon-aide-cyber-api/test/api/webhooks/routesAPIWebhooks.spec.ts
Toute saisie libre peut comporter des risques d’exposition d’informations sensibles et /ou personnelles
> [CORRECTION] Ne consigne plus le champ libre retourné par le formulaire de satisfaction lors du suivi du diagnostic

- mon-aide-cyber-api/src/administration/utilisateurs/modification-emails-de-comptes/commande.ts
On veut éviter une situation où la tâche d'administration va créer un compte avec un email qui existait déjà chez MAC.
Cette PR rajoute des contrôles pour avoir des sorties comme 👇
> [ADMIN] Aoute des vérifications avant de modifier un email

- mon-aide-cyber-api/package.json
- mon-aide-cyber-api/src/administration/utilisateurs/creer-compte-authentification/commande.ts
- mon-aide-cyber-api/src/administration/utilisateurs/recreer-compte-authentification/commande.ts
On veut pouvoir recréer un compte d'authentification classique pour un utilisateur MAC.
Cas nominal :
> [COMPTES UTILISATEURS ] Recréé un compte d'authentification utilisateur
